use super::{Instruction, exec};

/// Instruction lookup table.
#[rustfmt::skip]
pub const DECODE: [Instruction; 0x100] = [
    Instruction { code: 0x00, exec: exec::nop::default(),    repr: "NOP",            legacy: None },
    Instruction { code: 0x01, exec: exec::ldw::default(),    repr: "LD BC, n16",     legacy: None },
    Instruction { code: 0x02, exec: exec::ld::default(),     repr: "LD (BC), A",     legacy: None },
    Instruction { code: 0x03, exec: exec::incw::default(),   repr: "INC BC",         legacy: None },
    Instruction { code: 0x04, exec: exec::inc::default(),    repr: "INC B",          legacy: None },
    Instruction { code: 0x05, exec: exec::dec::default(),    repr: "DEC B",          legacy: None },
    Instruction { code: 0x06, exec: exec::ld::default(),     repr: "LD B, n8",       legacy: None },
    Instruction { code: 0x07, exec: exec::rlca::default(),   repr: "RLCA",           legacy: None },
    Instruction { code: 0x08, exec: exec::ldw::default(),    repr: "LD (a16), SP",   legacy: None },
    Instruction { code: 0x09, exec: exec::addw::default(),   repr: "ADD HL, BC",     legacy: None },
    Instruction { code: 0x0a, exec: exec::ld::default(),     repr: "LD A, (BC)",     legacy: None },
    Instruction { code: 0x0b, exec: exec::decw::default(),   repr: "DEC BC",         legacy: None },
    Instruction { code: 0x0c, exec: exec::inc::default(),    repr: "INC C",          legacy: None },
    Instruction { code: 0x0d, exec: exec::dec::default(),    repr: "DEC C",          legacy: None },
    Instruction { code: 0x0e, exec: exec::ld::default(),     repr: "LD C, n8",       legacy: None },
    Instruction { code: 0x0f, exec: exec::rrca::default(),   repr: "RRCA",           legacy: None },
    Instruction { code: 0x10, exec: exec::legacy,            repr: "STOP",           legacy: Some(exec::stop::default) },
    Instruction { code: 0x11, exec: exec::ldw::default(),    repr: "LD DE, (n16)",   legacy: None },
    Instruction { code: 0x12, exec: exec::ld::default(),     repr: "LD (DE), A",     legacy: None },
    Instruction { code: 0x13, exec: exec::incw::default(),   repr: "INC DE",         legacy: None },
    Instruction { code: 0x14, exec: exec::inc::default(),    repr: "INC D",          legacy: None },
    Instruction { code: 0x15, exec: exec::dec::default(),    repr: "DEC D",          legacy: None },
    Instruction { code: 0x16, exec: exec::ld::default(),     repr: "LD D, n8",       legacy: None },
    Instruction { code: 0x17, exec: exec::rla::default(),    repr: "RLA",            legacy: None },
    Instruction { code: 0x18, exec: exec::jr::default(),     repr: "JR e8",          legacy: None },
    Instruction { code: 0x19, exec: exec::addw::default(),   repr: "ADD HL, DE",     legacy: None },
    Instruction { code: 0x1a, exec: exec::ld::default(),     repr: "LD A, (DE)",     legacy: None },
    Instruction { code: 0x1b, exec: exec::decw::default(),   repr: "DEC DE",         legacy: None },
    Instruction { code: 0x1c, exec: exec::inc::default(),    repr: "INC E",          legacy: None },
    Instruction { code: 0x1d, exec: exec::dec::default(),    repr: "DEC E",          legacy: None },
    Instruction { code: 0x1e, exec: exec::ld::default(),     repr: "LD E, n8",       legacy: None },
    Instruction { code: 0x1f, exec: exec::rra::default(),    repr: "RRA",            legacy: None },
    Instruction { code: 0x20, exec: exec::jr::default(),     repr: "JR NZ, e8",      legacy: None },
    Instruction { code: 0x21, exec: exec::ldw::default(),    repr: "LD HL, n16",     legacy: None },
    Instruction { code: 0x22, exec: exec::ld::default(),     repr: "LD (HL+), A",    legacy: None },
    Instruction { code: 0x23, exec: exec::incw::default(),   repr: "INC HL",         legacy: None },
    Instruction { code: 0x24, exec: exec::inc::default(),    repr: "INC H",          legacy: None },
    Instruction { code: 0x25, exec: exec::dec::default(),    repr: "DEC H",          legacy: None },
    Instruction { code: 0x26, exec: exec::ld::default(),     repr: "LD H, n8",       legacy: None },
    Instruction { code: 0x27, exec: exec::daa::default(),    repr: "DAA",            legacy: None },
    Instruction { code: 0x28, exec: exec::jr::default(),     repr: "JR Z, e8",       legacy: None },
    Instruction { code: 0x29, exec: exec::addw::default(),   repr: "ADD HL, HL",     legacy: None },
    Instruction { code: 0x2a, exec: exec::ld::default(),     repr: "LD A, (HL+)",    legacy: None },
    Instruction { code: 0x2b, exec: exec::decw::default(),   repr: "DEC HL",         legacy: None },
    Instruction { code: 0x2c, exec: exec::inc::default(),    repr: "INC L",          legacy: None },
    Instruction { code: 0x2d, exec: exec::dec::default(),    repr: "DEC L",          legacy: None },
    Instruction { code: 0x2e, exec: exec::ld::default(),     repr: "LD L, n8",       legacy: None },
    Instruction { code: 0x2f, exec: exec::cpl::default(),    repr: "CPL",            legacy: None },
    Instruction { code: 0x30, exec: exec::jr::default(),     repr: "JR NC, e8",      legacy: None },
    Instruction { code: 0x31, exec: exec::ldw::default(),    repr: "LD SP, n16",     legacy: None },
    Instruction { code: 0x32, exec: exec::ld::default(),     repr: "LD (HL-), A",    legacy: None },
    Instruction { code: 0x33, exec: exec::incw::default(),   repr: "INC SP",         legacy: None },
    Instruction { code: 0x34, exec: exec::inc::default(),    repr: "INC (HL)",       legacy: None },
    Instruction { code: 0x35, exec: exec::dec::default(),    repr: "DEC (HL)",       legacy: None },
    Instruction { code: 0x36, exec: exec::ld::default(),     repr: "LD (HL), n8",    legacy: None },
    Instruction { code: 0x37, exec: exec::scf::default(),    repr: "SCF",            legacy: None },
    Instruction { code: 0x38, exec: exec::jr::default(),     repr: "JR C, e8",       legacy: None },
    Instruction { code: 0x39, exec: exec::addw::default(),   repr: "ADD HL, SP",     legacy: None },
    Instruction { code: 0x3a, exec: exec::ld::default(),     repr: "LD A, (HL-)",    legacy: None },
    Instruction { code: 0x3b, exec: exec::decw::default(),   repr: "DEC SP",         legacy: None },
    Instruction { code: 0x3c, exec: exec::inc::default(),    repr: "INC A",          legacy: None },
    Instruction { code: 0x3d, exec: exec::dec::default(),    repr: "DEC A",          legacy: None },
    Instruction { code: 0x3e, exec: exec::ld::default(),     repr: "LD A, n8",       legacy: None },
    Instruction { code: 0x3f, exec: exec::ccf::default(),    repr: "CCP",            legacy: None },
    Instruction { code: 0x40, exec: exec::ld::default(),     repr: "LD B, B",        legacy: None },
    Instruction { code: 0x41, exec: exec::ld::default(),     repr: "LD B, C",        legacy: None },
    Instruction { code: 0x42, exec: exec::ld::default(),     repr: "LD B, D",        legacy: None },
    Instruction { code: 0x43, exec: exec::ld::default(),     repr: "LD B, E",        legacy: None },
    Instruction { code: 0x44, exec: exec::ld::default(),     repr: "LD B, H",        legacy: None },
    Instruction { code: 0x45, exec: exec::ld::default(),     repr: "LD B, L",        legacy: None },
    Instruction { code: 0x46, exec: exec::ld::default(),     repr: "LD B, (HL)",     legacy: None },
    Instruction { code: 0x47, exec: exec::ld::default(),     repr: "LD B, A",        legacy: None },
    Instruction { code: 0x48, exec: exec::ld::default(),     repr: "LD C, B",        legacy: None },
    Instruction { code: 0x49, exec: exec::ld::default(),     repr: "LD C, C",        legacy: None },
    Instruction { code: 0x4a, exec: exec::ld::default(),     repr: "LD C, D",        legacy: None },
    Instruction { code: 0x4b, exec: exec::ld::default(),     repr: "LD C, E",        legacy: None },
    Instruction { code: 0x4c, exec: exec::ld::default(),     repr: "LD C, H",        legacy: None },
    Instruction { code: 0x4d, exec: exec::ld::default(),     repr: "LD C, L",        legacy: None },
    Instruction { code: 0x4e, exec: exec::ld::default(),     repr: "LD C, (HL)",     legacy: None },
    Instruction { code: 0x4f, exec: exec::ld::default(),     repr: "LD C, A",        legacy: None },
    Instruction { code: 0x50, exec: exec::ld::default(),     repr: "LD D, B",        legacy: None },
    Instruction { code: 0x51, exec: exec::ld::default(),     repr: "LD D, C",        legacy: None },
    Instruction { code: 0x52, exec: exec::ld::default(),     repr: "LD D, D",        legacy: None },
    Instruction { code: 0x53, exec: exec::ld::default(),     repr: "LD D, E",        legacy: None },
    Instruction { code: 0x54, exec: exec::ld::default(),     repr: "LD D, H",        legacy: None },
    Instruction { code: 0x55, exec: exec::ld::default(),     repr: "LD D, L",        legacy: None },
    Instruction { code: 0x56, exec: exec::ld::default(),     repr: "LD D, (HL)",     legacy: None },
    Instruction { code: 0x57, exec: exec::ld::default(),     repr: "LD D, A",        legacy: None },
    Instruction { code: 0x58, exec: exec::ld::default(),     repr: "LD E, B",        legacy: None },
    Instruction { code: 0x59, exec: exec::ld::default(),     repr: "LD E, C",        legacy: None },
    Instruction { code: 0x5a, exec: exec::ld::default(),     repr: "LD E, D",        legacy: None },
    Instruction { code: 0x5b, exec: exec::ld::default(),     repr: "LD E, E",        legacy: None },
    Instruction { code: 0x5c, exec: exec::ld::default(),     repr: "LD E, H",        legacy: None },
    Instruction { code: 0x5d, exec: exec::ld::default(),     repr: "LD E, L",        legacy: None },
    Instruction { code: 0x5e, exec: exec::ld::default(),     repr: "LD E, (HL)",     legacy: None },
    Instruction { code: 0x5f, exec: exec::ld::default(),     repr: "LD E, A",        legacy: None },
    Instruction { code: 0x60, exec: exec::ld::default(),     repr: "LD H, B",        legacy: None },
    Instruction { code: 0x61, exec: exec::ld::default(),     repr: "LD H, C",        legacy: None },
    Instruction { code: 0x62, exec: exec::ld::default(),     repr: "LD H, D",        legacy: None },
    Instruction { code: 0x63, exec: exec::ld::default(),     repr: "LD H, E",        legacy: None },
    Instruction { code: 0x64, exec: exec::ld::default(),     repr: "LD H, H",        legacy: None },
    Instruction { code: 0x65, exec: exec::ld::default(),     repr: "LD H, L",        legacy: None },
    Instruction { code: 0x66, exec: exec::ld::default(),     repr: "LD H, (HL)",     legacy: None },
    Instruction { code: 0x67, exec: exec::ld::default(),     repr: "LD H, A",        legacy: None },
    Instruction { code: 0x68, exec: exec::ld::default(),     repr: "LD L, B",        legacy: None },
    Instruction { code: 0x69, exec: exec::ld::default(),     repr: "LD L, C",        legacy: None },
    Instruction { code: 0x6a, exec: exec::ld::default(),     repr: "LD L, D",        legacy: None },
    Instruction { code: 0x6b, exec: exec::ld::default(),     repr: "LD L, E",        legacy: None },
    Instruction { code: 0x6c, exec: exec::ld::default(),     repr: "LD L, H",        legacy: None },
    Instruction { code: 0x6d, exec: exec::ld::default(),     repr: "LD L, L",        legacy: None },
    Instruction { code: 0x6e, exec: exec::ld::default(),     repr: "LD L, (HL)",     legacy: None },
    Instruction { code: 0x6f, exec: exec::ld::default(),     repr: "LD L, A",        legacy: None },
    Instruction { code: 0x70, exec: exec::ld::default(),     repr: "LD (HL), B",     legacy: None },
    Instruction { code: 0x71, exec: exec::ld::default(),     repr: "LD (HL), C",     legacy: None },
    Instruction { code: 0x72, exec: exec::ld::default(),     repr: "LD (HL), D",     legacy: None },
    Instruction { code: 0x73, exec: exec::ld::default(),     repr: "LD (HL), E",     legacy: None },
    Instruction { code: 0x74, exec: exec::ld::default(),     repr: "LD (HL), H",     legacy: None },
    Instruction { code: 0x75, exec: exec::ld::default(),     repr: "LD (HL), L",     legacy: None },
    Instruction { code: 0x76, exec: exec::halt::default(),   repr: "HALT",           legacy: None },
    Instruction { code: 0x77, exec: exec::ld::default(),     repr: "LD (HL), A",     legacy: None },
    Instruction { code: 0x78, exec: exec::ld::default(),     repr: "LD A, B",        legacy: None },
    Instruction { code: 0x79, exec: exec::ld::default(),     repr: "LD A, C",        legacy: None },
    Instruction { code: 0x7a, exec: exec::ld::default(),     repr: "LD A, D",        legacy: None },
    Instruction { code: 0x7b, exec: exec::ld::default(),     repr: "LD A, E",        legacy: None },
    Instruction { code: 0x7c, exec: exec::ld::default(),     repr: "LD A, H",        legacy: None },
    Instruction { code: 0x7d, exec: exec::ld::default(),     repr: "LD A, L",        legacy: None },
    Instruction { code: 0x7e, exec: exec::ld::default(),     repr: "LD A, (HL)",     legacy: None },
    Instruction { code: 0x7f, exec: exec::ld::default(),     repr: "LD A, A",        legacy: None },
    Instruction { code: 0x80, exec: exec::add::default(),    repr: "ADD A, B",       legacy: None },
    Instruction { code: 0x81, exec: exec::add::default(),    repr: "ADD A, C",       legacy: None },
    Instruction { code: 0x82, exec: exec::add::default(),    repr: "ADD A, D",       legacy: None },
    Instruction { code: 0x83, exec: exec::add::default(),    repr: "ADD A, E",       legacy: None },
    Instruction { code: 0x84, exec: exec::add::default(),    repr: "ADD A, H",       legacy: None },
    Instruction { code: 0x85, exec: exec::add::default(),    repr: "ADD A, L",       legacy: None },
    Instruction { code: 0x86, exec: exec::add::default(),    repr: "ADD A, (HL)",    legacy: None },
    Instruction { code: 0x87, exec: exec::add::default(),    repr: "ADD A, A",       legacy: None },
    Instruction { code: 0x88, exec: exec::adc::default(),    repr: "ADC A, B",       legacy: None },
    Instruction { code: 0x89, exec: exec::adc::default(),    repr: "ADC A, C",       legacy: None },
    Instruction { code: 0x8a, exec: exec::adc::default(),    repr: "ADC A, D",       legacy: None },
    Instruction { code: 0x8b, exec: exec::adc::default(),    repr: "ADC A, E",       legacy: None },
    Instruction { code: 0x8c, exec: exec::adc::default(),    repr: "ADC A, H",       legacy: None },
    Instruction { code: 0x8d, exec: exec::adc::default(),    repr: "ADC A, L",       legacy: None },
    Instruction { code: 0x8e, exec: exec::adc::default(),    repr: "ADC A, (HL)",    legacy: None },
    Instruction { code: 0x8f, exec: exec::adc::default(),    repr: "ADC A, A",       legacy: None },
    Instruction { code: 0x90, exec: exec::legacy,            repr: "SUB A, B",       legacy: Some(exec::sub::default) },
    Instruction { code: 0x91, exec: exec::legacy,            repr: "SUB A, C",       legacy: Some(exec::sub::default) },
    Instruction { code: 0x92, exec: exec::legacy,            repr: "SUB A, D",       legacy: Some(exec::sub::default) },
    Instruction { code: 0x93, exec: exec::legacy,            repr: "SUB A, E",       legacy: Some(exec::sub::default) },
    Instruction { code: 0x94, exec: exec::legacy,            repr: "SUB A, H",       legacy: Some(exec::sub::default) },
    Instruction { code: 0x95, exec: exec::legacy,            repr: "SUB A, L",       legacy: Some(exec::sub::default) },
    Instruction { code: 0x96, exec: exec::legacy,            repr: "SUB A, (HL)",    legacy: Some(exec::sub::default) },
    Instruction { code: 0x97, exec: exec::legacy,            repr: "SUB A, A",       legacy: Some(exec::sub::default) },
    Instruction { code: 0x98, exec: exec::sbc::default(),    repr: "SBC A, B",       legacy: None },
    Instruction { code: 0x99, exec: exec::sbc::default(),    repr: "SBC A, C",       legacy: None },
    Instruction { code: 0x9a, exec: exec::sbc::default(),    repr: "SBC A, D",       legacy: None },
    Instruction { code: 0x9b, exec: exec::sbc::default(),    repr: "SBC A, E",       legacy: None },
    Instruction { code: 0x9c, exec: exec::sbc::default(),    repr: "SBC A, H",       legacy: None },
    Instruction { code: 0x9d, exec: exec::sbc::default(),    repr: "SBC A, L",       legacy: None },
    Instruction { code: 0x9e, exec: exec::sbc::default(),    repr: "SBC A, (HL)",    legacy: None },
    Instruction { code: 0x9f, exec: exec::sbc::default(),    repr: "SBC A, A",       legacy: None },
    Instruction { code: 0xa0, exec: exec::and::default(),    repr: "AND A, B",       legacy: None },
    Instruction { code: 0xa1, exec: exec::and::default(),    repr: "AND A, C",       legacy: None },
    Instruction { code: 0xa2, exec: exec::and::default(),    repr: "AND A, D",       legacy: None },
    Instruction { code: 0xa3, exec: exec::and::default(),    repr: "AND A, E",       legacy: None },
    Instruction { code: 0xa4, exec: exec::and::default(),    repr: "AND A, H",       legacy: None },
    Instruction { code: 0xa5, exec: exec::and::default(),    repr: "AND A, L",       legacy: None },
    Instruction { code: 0xa6, exec: exec::and::default(),    repr: "AND A, (HL)",    legacy: None },
    Instruction { code: 0xa7, exec: exec::and::default(),    repr: "AND A, A",       legacy: None },
    Instruction { code: 0xa8, exec: exec::legacy,            repr: "XOR A, B",       legacy: Some(exec::xor::default) },
    Instruction { code: 0xa9, exec: exec::legacy,            repr: "XOR A, C",       legacy: Some(exec::xor::default) },
    Instruction { code: 0xaa, exec: exec::legacy,            repr: "XOR A, D",       legacy: Some(exec::xor::default) },
    Instruction { code: 0xab, exec: exec::legacy,            repr: "XOR A, E",       legacy: Some(exec::xor::default) },
    Instruction { code: 0xac, exec: exec::legacy,            repr: "XOR A, H",       legacy: Some(exec::xor::default) },
    Instruction { code: 0xad, exec: exec::legacy,            repr: "XOR A, L",       legacy: Some(exec::xor::default) },
    Instruction { code: 0xae, exec: exec::legacy,            repr: "XOR A, (HL)",    legacy: Some(exec::xor::default) },
    Instruction { code: 0xaf, exec: exec::legacy,            repr: "XOR A, A",       legacy: Some(exec::xor::default) },
    Instruction { code: 0xb0, exec: exec::or::default(),     repr: "OR A, B",        legacy: None },
    Instruction { code: 0xb1, exec: exec::or::default(),     repr: "OR A, C",        legacy: None },
    Instruction { code: 0xb2, exec: exec::or::default(),     repr: "OR A, D",        legacy: None },
    Instruction { code: 0xb3, exec: exec::or::default(),     repr: "OR A, E",        legacy: None },
    Instruction { code: 0xb4, exec: exec::or::default(),     repr: "OR A, H",        legacy: None },
    Instruction { code: 0xb5, exec: exec::or::default(),     repr: "OR A, L",        legacy: None },
    Instruction { code: 0xb6, exec: exec::or::default(),     repr: "OR A, (HL)",     legacy: None },
    Instruction { code: 0xb7, exec: exec::or::default(),     repr: "OR A, A",        legacy: None },
    Instruction { code: 0xb8, exec: exec::cp::default(),     repr: "CP A, B",        legacy: None },
    Instruction { code: 0xb9, exec: exec::cp::default(),     repr: "CP A, C",        legacy: None },
    Instruction { code: 0xba, exec: exec::cp::default(),     repr: "CP A, D",        legacy: None },
    Instruction { code: 0xbb, exec: exec::cp::default(),     repr: "CP A, E",        legacy: None },
    Instruction { code: 0xbc, exec: exec::cp::default(),     repr: "CP A, H",        legacy: None },
    Instruction { code: 0xbd, exec: exec::cp::default(),     repr: "CP A, L",        legacy: None },
    Instruction { code: 0xbe, exec: exec::cp::default(),     repr: "CP A, (HL)",     legacy: None },
    Instruction { code: 0xbf, exec: exec::cp::default(),     repr: "CP A, A",        legacy: None },
    Instruction { code: 0xc0, exec: exec::ret::default(),    repr: "RET NZ",         legacy: None },
    Instruction { code: 0xc1, exec: exec::pop::default(),    repr: "POP BC",         legacy: None },
    Instruction { code: 0xc2, exec: exec::jp::default(),     repr: "JP NZ, a16",     legacy: None },
    Instruction { code: 0xc3, exec: exec::jp::default(),     repr: "JP a16",         legacy: None },
    Instruction { code: 0xc4, exec: exec::call::default(),   repr: "CALL NZ, a16",   legacy: None },
    Instruction { code: 0xc5, exec: exec::push::default(),   repr: "PUSH BC",        legacy: None },
    Instruction { code: 0xc6, exec: exec::add::default(),    repr: "ADD A, n8",      legacy: None },
    Instruction { code: 0xc7, exec: exec::rst::default(),    repr: "RST 00H",        legacy: None },
    Instruction { code: 0xc8, exec: exec::ret::default(),    repr: "RET Z",          legacy: None },
    Instruction { code: 0xc9, exec: exec::ret::default(),    repr: "RET",            legacy: None },
    Instruction { code: 0xca, exec: exec::jp::default(),     repr: "JP Z, a16",      legacy: None },
    Instruction { code: 0xcb, exec: exec::prefix::default(), repr: "PREFIX",         legacy: None },
    Instruction { code: 0xcc, exec: exec::call::default(),   repr: "CALL Z, a16",    legacy: None },
    Instruction { code: 0xcd, exec: exec::call::default(),   repr: "CALL a16",       legacy: None },
    Instruction { code: 0xce, exec: exec::adc::default(),    repr: "ADC A, n8",      legacy: None },
    Instruction { code: 0xcf, exec: exec::rst::default(),    repr: "RST 08H",        legacy: None },
    Instruction { code: 0xd0, exec: exec::ret::default(),    repr: "RET NC",         legacy: None },
    Instruction { code: 0xd1, exec: exec::pop::default(),    repr: "POP DE",         legacy: None },
    Instruction { code: 0xd2, exec: exec::jp::default(),     repr: "JP NC, a16",     legacy: None },
    Instruction { code: 0xd3, exec: exec::legacy,            repr: "UNUSED",         legacy: Some(exec::unused::default) },
    Instruction { code: 0xd4, exec: exec::call::default(),   repr: "CALL NC, a16",   legacy: None },
    Instruction { code: 0xd5, exec: exec::push::default(),   repr: "PUSH DE",        legacy: None },
    Instruction { code: 0xd6, exec: exec::legacy,            repr: "SUB n8",         legacy: Some(exec::sub::default) },
    Instruction { code: 0xd7, exec: exec::rst::default(),    repr: "RST 10H",        legacy: None },
    Instruction { code: 0xd8, exec: exec::ret::default(),    repr: "RET C",          legacy: None },
    Instruction { code: 0xd9, exec: exec::reti::default(),   repr: "RETI",           legacy: None },
    Instruction { code: 0xda, exec: exec::jp::default(),     repr: "JP C, a16",      legacy: None },
    Instruction { code: 0xdb, exec: exec::legacy,            repr: "UNUSED",         legacy: Some(exec::unused::default) },
    Instruction { code: 0xdc, exec: exec::call::default(),   repr: "CALL C, a16",    legacy: None },
    Instruction { code: 0xdd, exec: exec::legacy,            repr: "UNUSED",         legacy: Some(exec::unused::default) },
    Instruction { code: 0xde, exec: exec::sbc::default(),    repr: "SBC A, n8",      legacy: None },
    Instruction { code: 0xdf, exec: exec::rst::default(),    repr: "RST 18H",        legacy: None },
    Instruction { code: 0xe0, exec: exec::ldh::default(),    repr: "LDH (a8), A",    legacy: None },
    Instruction { code: 0xe1, exec: exec::pop::default(),    repr: "POP HL",         legacy: None },
    Instruction { code: 0xe2, exec: exec::ldh::default(),    repr: "LD (C), A",      legacy: None },
    Instruction { code: 0xe3, exec: exec::legacy,            repr: "UNUSED",         legacy: Some(exec::unused::default) },
    Instruction { code: 0xe4, exec: exec::legacy,            repr: "UNUSED",         legacy: Some(exec::unused::default) },
    Instruction { code: 0xe5, exec: exec::push::default(),   repr: "PUSH HL",        legacy: None },
    Instruction { code: 0xe6, exec: exec::and::default(),    repr: "AND A, n8",      legacy: None },
    Instruction { code: 0xe7, exec: exec::rst::default(),    repr: "RST 20H",        legacy: None },
    Instruction { code: 0xe8, exec: exec::addw::default(),   repr: "ADD SP, e8",     legacy: None },
    Instruction { code: 0xe9, exec: exec::jp::default(),     repr: "JP HL",          legacy: None },
    Instruction { code: 0xea, exec: exec::ld::default(),     repr: "LD (a16), A",    legacy: None },
    Instruction { code: 0xeb, exec: exec::legacy,            repr: "UNUSED",         legacy: Some(exec::unused::default) },
    Instruction { code: 0xec, exec: exec::legacy,            repr: "UNUSED",         legacy: Some(exec::unused::default) },
    Instruction { code: 0xed, exec: exec::legacy,            repr: "UNUSED",         legacy: Some(exec::unused::default) },
    Instruction { code: 0xee, exec: exec::legacy,            repr: "XOR A, n8",      legacy: Some(exec::xor::default) },
    Instruction { code: 0xef, exec: exec::rst::default(),    repr: "RST 28H",        legacy: None },
    Instruction { code: 0xf0, exec: exec::ldh::default(),    repr: "LDH A, (a8)",    legacy: None },
    Instruction { code: 0xf1, exec: exec::pop::default(),    repr: "POP AF",         legacy: None },
    Instruction { code: 0xf2, exec: exec::ldh::default(),    repr: "LD A, (C)",      legacy: None },
    Instruction { code: 0xf3, exec: exec::di::default(),     repr: "DI",             legacy: None },
    Instruction { code: 0xf4, exec: exec::legacy,            repr: "UNUSED",         legacy: Some(exec::unused::default) },
    Instruction { code: 0xf5, exec: exec::push::default(),   repr: "PUSH AF",        legacy: None },
    Instruction { code: 0xf6, exec: exec::or::default(),     repr: "OR A, n8",       legacy: None },
    Instruction { code: 0xf7, exec: exec::rst::default(),    repr: "RST 30H",        legacy: None },
    Instruction { code: 0xf8, exec: exec::ldw::default(),    repr: "LD HL, SP + e8", legacy: None },
    Instruction { code: 0xf9, exec: exec::ldw::default(),    repr: "LD SP, HL",      legacy: None },
    Instruction { code: 0xfa, exec: exec::ld::default(),     repr: "LD A, (a16)",    legacy: None },
    Instruction { code: 0xfb, exec: exec::ei::default(),     repr: "EI",             legacy: None },
    Instruction { code: 0xfc, exec: exec::legacy,            repr: "UNUSED",         legacy: Some(exec::unused::default) },
    Instruction { code: 0xfd, exec: exec::legacy,            repr: "UNUSED",         legacy: Some(exec::unused::default) },
    Instruction { code: 0xfe, exec: exec::cp::default(),     repr: "CP A, n8",       legacy: None },
    Instruction { code: 0xff, exec: exec::rst::default(),    repr: "RST 38H",        legacy: None },
];

/// Prefix lookup table.
#[rustfmt::skip]
pub const PREFIX: [Instruction; 0x100] = [
    Instruction { code: 0x00, exec: exec::rlc::default(),  repr: "RLC B",       legacy: None },
    Instruction { code: 0x01, exec: exec::rlc::default(),  repr: "RLC C",       legacy: None },
    Instruction { code: 0x02, exec: exec::rlc::default(),  repr: "RLC D",       legacy: None },
    Instruction { code: 0x03, exec: exec::rlc::default(),  repr: "RLC E",       legacy: None },
    Instruction { code: 0x04, exec: exec::rlc::default(),  repr: "RLC H",       legacy: None },
    Instruction { code: 0x05, exec: exec::rlc::default(),  repr: "RLC L",       legacy: None },
    Instruction { code: 0x06, exec: exec::rlc::default(),  repr: "RLC (HL)",    legacy: None },
    Instruction { code: 0x07, exec: exec::rlc::default(),  repr: "RLC A",       legacy: None },
    Instruction { code: 0x08, exec: exec::rrc::default(),  repr: "RRC B",       legacy: None },
    Instruction { code: 0x09, exec: exec::rrc::default(),  repr: "RRC C",       legacy: None },
    Instruction { code: 0x0a, exec: exec::rrc::default(),  repr: "RRC D",       legacy: None },
    Instruction { code: 0x0b, exec: exec::rrc::default(),  repr: "RRC E",       legacy: None },
    Instruction { code: 0x0c, exec: exec::rrc::default(),  repr: "RRC H",       legacy: None },
    Instruction { code: 0x0d, exec: exec::rrc::default(),  repr: "RRC L",       legacy: None },
    Instruction { code: 0x0e, exec: exec::rrc::default(),  repr: "RRC (HL)",    legacy: None },
    Instruction { code: 0x0f, exec: exec::rrc::default(),  repr: "RRC A",       legacy: None },
    Instruction { code: 0x10, exec: exec::rl::default(),   repr: "RL B",        legacy: None },
    Instruction { code: 0x11, exec: exec::rl::default(),   repr: "RL C",        legacy: None },
    Instruction { code: 0x12, exec: exec::rl::default(),   repr: "RL D",        legacy: None },
    Instruction { code: 0x13, exec: exec::rl::default(),   repr: "RL E",        legacy: None },
    Instruction { code: 0x14, exec: exec::rl::default(),   repr: "RL H",        legacy: None },
    Instruction { code: 0x15, exec: exec::rl::default(),   repr: "RL L",        legacy: None },
    Instruction { code: 0x16, exec: exec::rl::default(),   repr: "RL (HL)",     legacy: None },
    Instruction { code: 0x17, exec: exec::rl::default(),   repr: "RL A",        legacy: None },
    Instruction { code: 0x18, exec: exec::rr::default(),   repr: "RR B",        legacy: None },
    Instruction { code: 0x19, exec: exec::rr::default(),   repr: "RR C",        legacy: None },
    Instruction { code: 0x1a, exec: exec::rr::default(),   repr: "RR D",        legacy: None },
    Instruction { code: 0x1b, exec: exec::rr::default(),   repr: "RR E",        legacy: None },
    Instruction { code: 0x1c, exec: exec::rr::default(),   repr: "RR H",        legacy: None },
    Instruction { code: 0x1d, exec: exec::rr::default(),   repr: "RR L",        legacy: None },
    Instruction { code: 0x1e, exec: exec::rr::default(),   repr: "RR (HL)",     legacy: None },
    Instruction { code: 0x1f, exec: exec::rr::default(),   repr: "RR A",        legacy: None },
    Instruction { code: 0x20, exec: exec::legacy,          repr: "SLA B",       legacy: Some(exec::sla::default) },
    Instruction { code: 0x21, exec: exec::legacy,          repr: "SLA C",       legacy: Some(exec::sla::default) },
    Instruction { code: 0x22, exec: exec::legacy,          repr: "SLA D",       legacy: Some(exec::sla::default) },
    Instruction { code: 0x23, exec: exec::legacy,          repr: "SLA E",       legacy: Some(exec::sla::default) },
    Instruction { code: 0x24, exec: exec::legacy,          repr: "SLA H",       legacy: Some(exec::sla::default) },
    Instruction { code: 0x25, exec: exec::legacy,          repr: "SLA L",       legacy: Some(exec::sla::default) },
    Instruction { code: 0x26, exec: exec::legacy,          repr: "SLA (HL)",    legacy: Some(exec::sla::default) },
    Instruction { code: 0x27, exec: exec::legacy,          repr: "SLA A",       legacy: Some(exec::sla::default) },
    Instruction { code: 0x28, exec: exec::legacy,          repr: "SRA B",       legacy: Some(exec::sra::default) },
    Instruction { code: 0x29, exec: exec::legacy,          repr: "SRA C",       legacy: Some(exec::sra::default) },
    Instruction { code: 0x2a, exec: exec::legacy,          repr: "SRA D",       legacy: Some(exec::sra::default) },
    Instruction { code: 0x2b, exec: exec::legacy,          repr: "SRA E",       legacy: Some(exec::sra::default) },
    Instruction { code: 0x2c, exec: exec::legacy,          repr: "SRA H",       legacy: Some(exec::sra::default) },
    Instruction { code: 0x2d, exec: exec::legacy,          repr: "SRA L",       legacy: Some(exec::sra::default) },
    Instruction { code: 0x2e, exec: exec::legacy,          repr: "SRA (HL)",    legacy: Some(exec::sra::default) },
    Instruction { code: 0x2f, exec: exec::legacy,          repr: "SRA A",       legacy: Some(exec::sra::default) },
    Instruction { code: 0x30, exec: exec::legacy,          repr: "SWAP B",      legacy: Some(exec::swap::default) },
    Instruction { code: 0x31, exec: exec::legacy,          repr: "SWAP C",      legacy: Some(exec::swap::default) },
    Instruction { code: 0x32, exec: exec::legacy,          repr: "SWAP D",      legacy: Some(exec::swap::default) },
    Instruction { code: 0x33, exec: exec::legacy,          repr: "SWAP E",      legacy: Some(exec::swap::default) },
    Instruction { code: 0x34, exec: exec::legacy,          repr: "SWAP H",      legacy: Some(exec::swap::default) },
    Instruction { code: 0x35, exec: exec::legacy,          repr: "SWAP L",      legacy: Some(exec::swap::default) },
    Instruction { code: 0x36, exec: exec::legacy,          repr: "SWAP (HL)",   legacy: Some(exec::swap::default) },
    Instruction { code: 0x37, exec: exec::legacy,          repr: "SWAP A",      legacy: Some(exec::swap::default) },
    Instruction { code: 0x38, exec: exec::legacy,          repr: "SRL B",       legacy: Some(exec::srl::default) },
    Instruction { code: 0x39, exec: exec::legacy,          repr: "SRL C",       legacy: Some(exec::srl::default) },
    Instruction { code: 0x3a, exec: exec::legacy,          repr: "SRL D",       legacy: Some(exec::srl::default) },
    Instruction { code: 0x3b, exec: exec::legacy,          repr: "SRL E",       legacy: Some(exec::srl::default) },
    Instruction { code: 0x3c, exec: exec::legacy,          repr: "SRL H",       legacy: Some(exec::srl::default) },
    Instruction { code: 0x3d, exec: exec::legacy,          repr: "SRL L",       legacy: Some(exec::srl::default) },
    Instruction { code: 0x3e, exec: exec::legacy,          repr: "SRL (HL)",    legacy: Some(exec::srl::default) },
    Instruction { code: 0x3f, exec: exec::legacy,          repr: "SRL A",       legacy: Some(exec::srl::default) },
    Instruction { code: 0x40, exec: exec::bit::default(),  repr: "BIT 0, B",    legacy: None },
    Instruction { code: 0x41, exec: exec::bit::default(),  repr: "BIT 0, C",    legacy: None },
    Instruction { code: 0x42, exec: exec::bit::default(),  repr: "BIT 0, D",    legacy: None },
    Instruction { code: 0x43, exec: exec::bit::default(),  repr: "BIT 0, E",    legacy: None },
    Instruction { code: 0x44, exec: exec::bit::default(),  repr: "BIT 0, H",    legacy: None },
    Instruction { code: 0x45, exec: exec::bit::default(),  repr: "BIT 0, L",    legacy: None },
    Instruction { code: 0x46, exec: exec::bit::default(),  repr: "BIT 0, (HL)", legacy: None },
    Instruction { code: 0x47, exec: exec::bit::default(),  repr: "BIT 0, A",    legacy: None },
    Instruction { code: 0x48, exec: exec::bit::default(),  repr: "BIT 1, B",    legacy: None },
    Instruction { code: 0x49, exec: exec::bit::default(),  repr: "BIT 1, C",    legacy: None },
    Instruction { code: 0x4a, exec: exec::bit::default(),  repr: "BIT 1, D",    legacy: None },
    Instruction { code: 0x4b, exec: exec::bit::default(),  repr: "BIT 1, E",    legacy: None },
    Instruction { code: 0x4c, exec: exec::bit::default(),  repr: "BIT 1, H",    legacy: None },
    Instruction { code: 0x4d, exec: exec::bit::default(),  repr: "BIT 1, L",    legacy: None },
    Instruction { code: 0x4e, exec: exec::bit::default(),  repr: "BIT 1, (HL)", legacy: None },
    Instruction { code: 0x4f, exec: exec::bit::default(),  repr: "BIT 1, A",    legacy: None },
    Instruction { code: 0x50, exec: exec::bit::default(),  repr: "BIT 2, B",    legacy: None },
    Instruction { code: 0x51, exec: exec::bit::default(),  repr: "BIT 2, C",    legacy: None },
    Instruction { code: 0x52, exec: exec::bit::default(),  repr: "BIT 2, D",    legacy: None },
    Instruction { code: 0x53, exec: exec::bit::default(),  repr: "BIT 2, E",    legacy: None },
    Instruction { code: 0x54, exec: exec::bit::default(),  repr: "BIT 2, H",    legacy: None },
    Instruction { code: 0x55, exec: exec::bit::default(),  repr: "BIT 2, L",    legacy: None },
    Instruction { code: 0x56, exec: exec::bit::default(),  repr: "BIT 2, (HL)", legacy: None },
    Instruction { code: 0x57, exec: exec::bit::default(),  repr: "BIT 2, A",    legacy: None },
    Instruction { code: 0x58, exec: exec::bit::default(),  repr: "BIT 3, B",    legacy: None },
    Instruction { code: 0x59, exec: exec::bit::default(),  repr: "BIT 3, C",    legacy: None },
    Instruction { code: 0x5a, exec: exec::bit::default(),  repr: "BIT 3, D",    legacy: None },
    Instruction { code: 0x5b, exec: exec::bit::default(),  repr: "BIT 3, E",    legacy: None },
    Instruction { code: 0x5c, exec: exec::bit::default(),  repr: "BIT 3, H",    legacy: None },
    Instruction { code: 0x5d, exec: exec::bit::default(),  repr: "BIT 3, L",    legacy: None },
    Instruction { code: 0x5e, exec: exec::bit::default(),  repr: "BIT 3, (HL)", legacy: None },
    Instruction { code: 0x5f, exec: exec::bit::default(),  repr: "BIT 3, A",    legacy: None },
    Instruction { code: 0x60, exec: exec::bit::default(),  repr: "BIT 4, B",    legacy: None },
    Instruction { code: 0x61, exec: exec::bit::default(),  repr: "BIT 4, C",    legacy: None },
    Instruction { code: 0x62, exec: exec::bit::default(),  repr: "BIT 4, D",    legacy: None },
    Instruction { code: 0x63, exec: exec::bit::default(),  repr: "BIT 4, E",    legacy: None },
    Instruction { code: 0x64, exec: exec::bit::default(),  repr: "BIT 4, H",    legacy: None },
    Instruction { code: 0x65, exec: exec::bit::default(),  repr: "BIT 4, L",    legacy: None },
    Instruction { code: 0x66, exec: exec::bit::default(),  repr: "BIT 4, (HL)", legacy: None },
    Instruction { code: 0x67, exec: exec::bit::default(),  repr: "BIT 4, A",    legacy: None },
    Instruction { code: 0x68, exec: exec::bit::default(),  repr: "BIT 5, B",    legacy: None },
    Instruction { code: 0x69, exec: exec::bit::default(),  repr: "BIT 5, C",    legacy: None },
    Instruction { code: 0x6a, exec: exec::bit::default(),  repr: "BIT 5, D",    legacy: None },
    Instruction { code: 0x6b, exec: exec::bit::default(),  repr: "BIT 5, E",    legacy: None },
    Instruction { code: 0x6c, exec: exec::bit::default(),  repr: "BIT 5, H",    legacy: None },
    Instruction { code: 0x6d, exec: exec::bit::default(),  repr: "BIT 5, L",    legacy: None },
    Instruction { code: 0x6e, exec: exec::bit::default(),  repr: "BIT 5, (HL)", legacy: None },
    Instruction { code: 0x6f, exec: exec::bit::default(),  repr: "BIT 5, A",    legacy: None },
    Instruction { code: 0x70, exec: exec::bit::default(),  repr: "BIT 6, B",    legacy: None },
    Instruction { code: 0x71, exec: exec::bit::default(),  repr: "BIT 6, C",    legacy: None },
    Instruction { code: 0x72, exec: exec::bit::default(),  repr: "BIT 6, D",    legacy: None },
    Instruction { code: 0x73, exec: exec::bit::default(),  repr: "BIT 6, E",    legacy: None },
    Instruction { code: 0x74, exec: exec::bit::default(),  repr: "BIT 6, H",    legacy: None },
    Instruction { code: 0x75, exec: exec::bit::default(),  repr: "BIT 6, L",    legacy: None },
    Instruction { code: 0x76, exec: exec::bit::default(),  repr: "BIT 6, (HL)", legacy: None },
    Instruction { code: 0x77, exec: exec::bit::default(),  repr: "BIT 6, A",    legacy: None },
    Instruction { code: 0x78, exec: exec::bit::default(),  repr: "BIT 7, B",    legacy: None },
    Instruction { code: 0x79, exec: exec::bit::default(),  repr: "BIT 7, C",    legacy: None },
    Instruction { code: 0x7a, exec: exec::bit::default(),  repr: "BIT 7, D",    legacy: None },
    Instruction { code: 0x7b, exec: exec::bit::default(),  repr: "BIT 7, E",    legacy: None },
    Instruction { code: 0x7c, exec: exec::bit::default(),  repr: "BIT 7, H",    legacy: None },
    Instruction { code: 0x7d, exec: exec::bit::default(),  repr: "BIT 7, L",    legacy: None },
    Instruction { code: 0x7e, exec: exec::bit::default(),  repr: "BIT 7, (HL)", legacy: None },
    Instruction { code: 0x7f, exec: exec::bit::default(),  repr: "BIT 7, A",    legacy: None },
    Instruction { code: 0x80, exec: exec::res::default(),  repr: "RES 0, B",    legacy: None },
    Instruction { code: 0x81, exec: exec::res::default(),  repr: "RES 0, C",    legacy: None },
    Instruction { code: 0x82, exec: exec::res::default(),  repr: "RES 0, D",    legacy: None },
    Instruction { code: 0x83, exec: exec::res::default(),  repr: "RES 0, E",    legacy: None },
    Instruction { code: 0x84, exec: exec::res::default(),  repr: "RES 0, H",    legacy: None },
    Instruction { code: 0x85, exec: exec::res::default(),  repr: "RES 0, L",    legacy: None },
    Instruction { code: 0x86, exec: exec::res::default(),  repr: "RES 0, (HL)", legacy: None },
    Instruction { code: 0x87, exec: exec::res::default(),  repr: "RES 0, A",    legacy: None },
    Instruction { code: 0x88, exec: exec::res::default(),  repr: "RES 1, B",    legacy: None },
    Instruction { code: 0x89, exec: exec::res::default(),  repr: "RES 1, C",    legacy: None },
    Instruction { code: 0x8a, exec: exec::res::default(),  repr: "RES 1, D",    legacy: None },
    Instruction { code: 0x8b, exec: exec::res::default(),  repr: "RES 1, E",    legacy: None },
    Instruction { code: 0x8c, exec: exec::res::default(),  repr: "RES 1, H",    legacy: None },
    Instruction { code: 0x8d, exec: exec::res::default(),  repr: "RES 1, L",    legacy: None },
    Instruction { code: 0x8e, exec: exec::res::default(),  repr: "RES 1, (HL)", legacy: None },
    Instruction { code: 0x8f, exec: exec::res::default(),  repr: "RES 1, A",    legacy: None },
    Instruction { code: 0x90, exec: exec::res::default(),  repr: "RES 2, B",    legacy: None },
    Instruction { code: 0x91, exec: exec::res::default(),  repr: "RES 2, C",    legacy: None },
    Instruction { code: 0x92, exec: exec::res::default(),  repr: "RES 2, D",    legacy: None },
    Instruction { code: 0x93, exec: exec::res::default(),  repr: "RES 2, E",    legacy: None },
    Instruction { code: 0x94, exec: exec::res::default(),  repr: "RES 2, H",    legacy: None },
    Instruction { code: 0x95, exec: exec::res::default(),  repr: "RES 2, L",    legacy: None },
    Instruction { code: 0x96, exec: exec::res::default(),  repr: "RES 2, (HL)", legacy: None },
    Instruction { code: 0x97, exec: exec::res::default(),  repr: "RES 2, A",    legacy: None },
    Instruction { code: 0x98, exec: exec::res::default(),  repr: "RES 3, B",    legacy: None },
    Instruction { code: 0x99, exec: exec::res::default(),  repr: "RES 3, C",    legacy: None },
    Instruction { code: 0x9a, exec: exec::res::default(),  repr: "RES 3, D",    legacy: None },
    Instruction { code: 0x9b, exec: exec::res::default(),  repr: "RES 3, E",    legacy: None },
    Instruction { code: 0x9c, exec: exec::res::default(),  repr: "RES 3, H",    legacy: None },
    Instruction { code: 0x9d, exec: exec::res::default(),  repr: "RES 3, L",    legacy: None },
    Instruction { code: 0x9e, exec: exec::res::default(),  repr: "RES 3, (HL)", legacy: None },
    Instruction { code: 0x9f, exec: exec::res::default(),  repr: "RES 3, A",    legacy: None },
    Instruction { code: 0xa0, exec: exec::res::default(),  repr: "RES 4, B",    legacy: None },
    Instruction { code: 0xa1, exec: exec::res::default(),  repr: "RES 4, C",    legacy: None },
    Instruction { code: 0xa2, exec: exec::res::default(),  repr: "RES 4, D",    legacy: None },
    Instruction { code: 0xa3, exec: exec::res::default(),  repr: "RES 4, E",    legacy: None },
    Instruction { code: 0xa4, exec: exec::res::default(),  repr: "RES 4, H",    legacy: None },
    Instruction { code: 0xa5, exec: exec::res::default(),  repr: "RES 4, L",    legacy: None },
    Instruction { code: 0xa6, exec: exec::res::default(),  repr: "RES 4, (HL)", legacy: None },
    Instruction { code: 0xa7, exec: exec::res::default(),  repr: "RES 4, A",    legacy: None },
    Instruction { code: 0xa8, exec: exec::res::default(),  repr: "RES 5, B",    legacy: None },
    Instruction { code: 0xa9, exec: exec::res::default(),  repr: "RES 5, C",    legacy: None },
    Instruction { code: 0xaa, exec: exec::res::default(),  repr: "RES 5, D",    legacy: None },
    Instruction { code: 0xab, exec: exec::res::default(),  repr: "RES 5, E",    legacy: None },
    Instruction { code: 0xac, exec: exec::res::default(),  repr: "RES 5, H",    legacy: None },
    Instruction { code: 0xad, exec: exec::res::default(),  repr: "RES 5, L",    legacy: None },
    Instruction { code: 0xae, exec: exec::res::default(),  repr: "RES 5, (HL)", legacy: None },
    Instruction { code: 0xaf, exec: exec::res::default(),  repr: "RES 5, A",    legacy: None },
    Instruction { code: 0xb0, exec: exec::res::default(),  repr: "RES 6, B",    legacy: None },
    Instruction { code: 0xb1, exec: exec::res::default(),  repr: "RES 6, C",    legacy: None },
    Instruction { code: 0xb2, exec: exec::res::default(),  repr: "RES 6, D",    legacy: None },
    Instruction { code: 0xb3, exec: exec::res::default(),  repr: "RES 6, E",    legacy: None },
    Instruction { code: 0xb4, exec: exec::res::default(),  repr: "RES 6, H",    legacy: None },
    Instruction { code: 0xb5, exec: exec::res::default(),  repr: "RES 6, L",    legacy: None },
    Instruction { code: 0xb6, exec: exec::res::default(),  repr: "RES 6, (HL)", legacy: None },
    Instruction { code: 0xb7, exec: exec::res::default(),  repr: "RES 6, A",    legacy: None },
    Instruction { code: 0xb8, exec: exec::res::default(),  repr: "RES 7, B",    legacy: None },
    Instruction { code: 0xb9, exec: exec::res::default(),  repr: "RES 7, C",    legacy: None },
    Instruction { code: 0xba, exec: exec::res::default(),  repr: "RES 7, D",    legacy: None },
    Instruction { code: 0xbb, exec: exec::res::default(),  repr: "RES 7, E",    legacy: None },
    Instruction { code: 0xbc, exec: exec::res::default(),  repr: "RES 7, H",    legacy: None },
    Instruction { code: 0xbd, exec: exec::res::default(),  repr: "RES 7, L",    legacy: None },
    Instruction { code: 0xbe, exec: exec::res::default(),  repr: "RES 7, (HL)", legacy: None },
    Instruction { code: 0xbf, exec: exec::res::default(),  repr: "RES 7, A",    legacy: None },
    Instruction { code: 0xc0, exec: exec::legacy,          repr: "SET 0, B",    legacy: Some(exec::set::default) },
    Instruction { code: 0xc1, exec: exec::legacy,          repr: "SET 0, C",    legacy: Some(exec::set::default) },
    Instruction { code: 0xc2, exec: exec::legacy,          repr: "SET 0, D",    legacy: Some(exec::set::default) },
    Instruction { code: 0xc3, exec: exec::legacy,          repr: "SET 0, E",    legacy: Some(exec::set::default) },
    Instruction { code: 0xc4, exec: exec::legacy,          repr: "SET 0, H",    legacy: Some(exec::set::default) },
    Instruction { code: 0xc5, exec: exec::legacy,          repr: "SET 0, L",    legacy: Some(exec::set::default) },
    Instruction { code: 0xc6, exec: exec::legacy,          repr: "SET 0, (HL)", legacy: Some(exec::set::default) },
    Instruction { code: 0xc7, exec: exec::legacy,          repr: "SET 0, A",    legacy: Some(exec::set::default) },
    Instruction { code: 0xc8, exec: exec::legacy,          repr: "SET 1, B",    legacy: Some(exec::set::default) },
    Instruction { code: 0xc9, exec: exec::legacy,          repr: "SET 1, C",    legacy: Some(exec::set::default) },
    Instruction { code: 0xca, exec: exec::legacy,          repr: "SET 1, D",    legacy: Some(exec::set::default) },
    Instruction { code: 0xcb, exec: exec::legacy,          repr: "SET 1, E",    legacy: Some(exec::set::default) },
    Instruction { code: 0xcc, exec: exec::legacy,          repr: "SET 1, H",    legacy: Some(exec::set::default) },
    Instruction { code: 0xcd, exec: exec::legacy,          repr: "SET 1, L",    legacy: Some(exec::set::default) },
    Instruction { code: 0xce, exec: exec::legacy,          repr: "SET 1, (HL)", legacy: Some(exec::set::default) },
    Instruction { code: 0xcf, exec: exec::legacy,          repr: "SET 1, A",    legacy: Some(exec::set::default) },
    Instruction { code: 0xd0, exec: exec::legacy,          repr: "SET 2, B",    legacy: Some(exec::set::default) },
    Instruction { code: 0xd1, exec: exec::legacy,          repr: "SET 2, C",    legacy: Some(exec::set::default) },
    Instruction { code: 0xd2, exec: exec::legacy,          repr: "SET 2, D",    legacy: Some(exec::set::default) },
    Instruction { code: 0xd3, exec: exec::legacy,          repr: "SET 2, E",    legacy: Some(exec::set::default) },
    Instruction { code: 0xd4, exec: exec::legacy,          repr: "SET 2, H",    legacy: Some(exec::set::default) },
    Instruction { code: 0xd5, exec: exec::legacy,          repr: "SET 2, L",    legacy: Some(exec::set::default) },
    Instruction { code: 0xd6, exec: exec::legacy,          repr: "SET 2, (HL)", legacy: Some(exec::set::default) },
    Instruction { code: 0xd7, exec: exec::legacy,          repr: "SET 2, A",    legacy: Some(exec::set::default) },
    Instruction { code: 0xd8, exec: exec::legacy,          repr: "SET 3, B",    legacy: Some(exec::set::default) },
    Instruction { code: 0xd9, exec: exec::legacy,          repr: "SET 3, C",    legacy: Some(exec::set::default) },
    Instruction { code: 0xda, exec: exec::legacy,          repr: "SET 3, D",    legacy: Some(exec::set::default) },
    Instruction { code: 0xdb, exec: exec::legacy,          repr: "SET 3, E",    legacy: Some(exec::set::default) },
    Instruction { code: 0xdc, exec: exec::legacy,          repr: "SET 3, H",    legacy: Some(exec::set::default) },
    Instruction { code: 0xdd, exec: exec::legacy,          repr: "SET 3, L",    legacy: Some(exec::set::default) },
    Instruction { code: 0xde, exec: exec::legacy,          repr: "SET 3, (HL)", legacy: Some(exec::set::default) },
    Instruction { code: 0xdf, exec: exec::legacy,          repr: "SET 3, A",    legacy: Some(exec::set::default) },
    Instruction { code: 0xe0, exec: exec::legacy,          repr: "SET 4, B",    legacy: Some(exec::set::default) },
    Instruction { code: 0xe1, exec: exec::legacy,          repr: "SET 4, C",    legacy: Some(exec::set::default) },
    Instruction { code: 0xe2, exec: exec::legacy,          repr: "SET 4, D",    legacy: Some(exec::set::default) },
    Instruction { code: 0xe3, exec: exec::legacy,          repr: "SET 4, E",    legacy: Some(exec::set::default) },
    Instruction { code: 0xe4, exec: exec::legacy,          repr: "SET 4, H",    legacy: Some(exec::set::default) },
    Instruction { code: 0xe5, exec: exec::legacy,          repr: "SET 4, L",    legacy: Some(exec::set::default) },
    Instruction { code: 0xe6, exec: exec::legacy,          repr: "SET 4, (HL)", legacy: Some(exec::set::default) },
    Instruction { code: 0xe7, exec: exec::legacy,          repr: "SET 4, A",    legacy: Some(exec::set::default) },
    Instruction { code: 0xe8, exec: exec::legacy,          repr: "SET 5, B",    legacy: Some(exec::set::default) },
    Instruction { code: 0xe9, exec: exec::legacy,          repr: "SET 5, C",    legacy: Some(exec::set::default) },
    Instruction { code: 0xea, exec: exec::legacy,          repr: "SET 5, D",    legacy: Some(exec::set::default) },
    Instruction { code: 0xeb, exec: exec::legacy,          repr: "SET 5, E",    legacy: Some(exec::set::default) },
    Instruction { code: 0xec, exec: exec::legacy,          repr: "SET 5, H",    legacy: Some(exec::set::default) },
    Instruction { code: 0xed, exec: exec::legacy,          repr: "SET 5, L",    legacy: Some(exec::set::default) },
    Instruction { code: 0xee, exec: exec::legacy,          repr: "SET 5, (HL)", legacy: Some(exec::set::default) },
    Instruction { code: 0xef, exec: exec::legacy,          repr: "SET 5, A",    legacy: Some(exec::set::default) },
    Instruction { code: 0xf0, exec: exec::legacy,          repr: "SET 6, B",    legacy: Some(exec::set::default) },
    Instruction { code: 0xf1, exec: exec::legacy,          repr: "SET 6, C",    legacy: Some(exec::set::default) },
    Instruction { code: 0xf2, exec: exec::legacy,          repr: "SET 6, D",    legacy: Some(exec::set::default) },
    Instruction { code: 0xf3, exec: exec::legacy,          repr: "SET 6, E",    legacy: Some(exec::set::default) },
    Instruction { code: 0xf4, exec: exec::legacy,          repr: "SET 6, H",    legacy: Some(exec::set::default) },
    Instruction { code: 0xf5, exec: exec::legacy,          repr: "SET 6, L",    legacy: Some(exec::set::default) },
    Instruction { code: 0xf6, exec: exec::legacy,          repr: "SET 6, (HL)", legacy: Some(exec::set::default) },
    Instruction { code: 0xf7, exec: exec::legacy,          repr: "SET 6, A",    legacy: Some(exec::set::default) },
    Instruction { code: 0xf8, exec: exec::legacy,          repr: "SET 7, B",    legacy: Some(exec::set::default) },
    Instruction { code: 0xf9, exec: exec::legacy,          repr: "SET 7, C",    legacy: Some(exec::set::default) },
    Instruction { code: 0xfa, exec: exec::legacy,          repr: "SET 7, D",    legacy: Some(exec::set::default) },
    Instruction { code: 0xfb, exec: exec::legacy,          repr: "SET 7, E",    legacy: Some(exec::set::default) },
    Instruction { code: 0xfc, exec: exec::legacy,          repr: "SET 7, H",    legacy: Some(exec::set::default) },
    Instruction { code: 0xfd, exec: exec::legacy,          repr: "SET 7, L",    legacy: Some(exec::set::default) },
    Instruction { code: 0xfe, exec: exec::legacy,          repr: "SET 7, (HL)", legacy: Some(exec::set::default) },
    Instruction { code: 0xff, exec: exec::legacy,          repr: "SET 7, A",    legacy: Some(exec::set::default) },
];
