#                       __
#                      /\ \
#  _ __   __  __     __\ \ \____  __  __
# /\`'__\/\ \/\ \  /'_ `\ \ '__`\/\ \/\ \
# \ \ \/ \ \ \_\ \/\ \L\ \ \ \L\ \ \ \_\ \
#  \ \_\  \ \____/\ \____ \ \_,__/\/`____ \
#   \/_/   \/___/  \/___L\ \/___/  `/___/> \
#                    /\____/          /\___/
#                    \_/__/           \/__/
#
# This file, usually found at `$XDG_CONFIG_HOME/rugby/config.toml`, can be used
# to store persistent configuration for `rugby`.
#
# When options are specified in multiple locations, they will be applied with
# the following precedence: cli > env > file. This means these options may be
# overridden when running the program.
#
# Any relative paths specified in this file are resolved relative to this file's
# parent directory. Use `--conf` on the command-line to provide an alternate
# location for this file.

[general]
# DMG color palette
#
# Value must be a named preset or customized as follows:
# palette = { custom = ["#222", "#666", "#aaa", "#ddd"] }
palette = "morris"
# Simulated clock speed
#
# Value must be a named preset or customized as follows:
# speed   = { fps = 90 }      # runs at 1.50x
# speed   = { hz  = 3145728 } # runs at 0.75x
speed   = "actual"

[cartridge]
# Check cartridge integrity
check = true
# Force cartridge construction
force = false
# Cartridge RAM persistence
save = "always"

[hardware]
# Boot ROM image file
boot = "../../../roms/boot/sameboy/dmg_boot.bin"
