//! Instruction state machine.

use std::fmt::{Debug, Display};

use super::{Cpu, Flag, Ime, Status};
use crate::hw::pic::Interrupt;

mod exec;

/// CPU instruction state.
///
/// Stores the currently executing instruction together with its state. Can be
/// started and resumed.
///
/// TODO: Eventually replace with a generator once stable.
#[derive(Clone)]
pub struct Instruction {
    opcode: u8,
    fmt: &'static str,
    exec: fn(Self, &mut Cpu) -> Option<Self>,
    stack: Vec<u8>,
}

impl Instruction {
    pub fn new(opcode: u8) -> Self {
        DECODE[opcode as usize].clone()
    }

    pub fn prefix(opcode: u8) -> Self {
        PREFIX[opcode as usize].clone()
    }

    pub fn int(int: Interrupt) -> Self {
        Self {
            opcode: 0x00,
            fmt: int.repr(),
            exec: exec::int::start,
            stack: vec![int.handler()],
        }
    }

    pub fn exec(self, cpu: &mut Cpu) -> Option<Self> {
        (self.exec)(self, cpu)
    }
}

impl Debug for Instruction {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("Instruction")
            .field("fmt", &self.fmt)
            .field("opcode", &self.opcode)
            .field("stack", &self.stack)
            .finish()
    }
}

impl Display for Instruction {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", self.fmt)
    }
}

/// Helper functions.
mod helpers {
    use super::*;

    /// Get an 8-bit register operand.
    pub fn get_op8(cpu: &mut Cpu, idx: u8) -> u8 {
        match idx {
            0x0 => *cpu.regs.b,
            0x1 => *cpu.regs.c,
            0x2 => *cpu.regs.d,
            0x3 => *cpu.regs.e,
            0x4 => *cpu.regs.h,
            0x5 => *cpu.regs.l,
            0x6 => cpu.readbyte(),
            0x7 => *cpu.regs.a,
            _ => panic!("Illegal register."),
        }
    }

    /// Set an 8-bit register operand.
    pub fn set_op8(cpu: &mut Cpu, idx: u8, value: u8) {
        match idx {
            0x0 => *cpu.regs.b = value,
            0x1 => *cpu.regs.c = value,
            0x2 => *cpu.regs.d = value,
            0x3 => *cpu.regs.e = value,
            0x4 => *cpu.regs.h = value,
            0x5 => *cpu.regs.l = value,
            0x6 => cpu.writebyte(value),
            0x7 => *cpu.regs.a = value,
            _ => panic!("Illegal register."),
        };
    }
}

/// Instruction lookup table.
#[rustfmt::skip]
const DECODE: [Instruction; 0x100] = [
    Instruction { opcode: 0x00, fmt: "NOP",           exec: exec::nop::start,    stack: Vec::new() },
    Instruction { opcode: 0x01, fmt: "LD BC, d16",    exec: exec::ldw::start,    stack: Vec::new() },
    Instruction { opcode: 0x02, fmt: "LD (BC), A",    exec: exec::ld::start,     stack: Vec::new() },
    Instruction { opcode: 0x03, fmt: "INC BC",        exec: exec::incw::start,   stack: Vec::new() },
    Instruction { opcode: 0x04, fmt: "INC B",         exec: exec::inc::start,    stack: Vec::new() },
    Instruction { opcode: 0x05, fmt: "DEC B",         exec: exec::dec::start,    stack: Vec::new() },
    Instruction { opcode: 0x06, fmt: "LD B, d8",      exec: exec::ld::start,     stack: Vec::new() },
    Instruction { opcode: 0x07, fmt: "RLCA",          exec: exec::rlca::start,   stack: Vec::new() },
    Instruction { opcode: 0x08, fmt: "LD (a16), SP",  exec: exec::ldw::start,    stack: Vec::new() },
    Instruction { opcode: 0x09, fmt: "ADD HL, BC",    exec: exec::addw::start,   stack: Vec::new() },
    Instruction { opcode: 0x0a, fmt: "LD A, (BC)",    exec: exec::ld::start,     stack: Vec::new() },
    Instruction { opcode: 0x0b, fmt: "DEC BC",        exec: exec::decw::start,   stack: Vec::new() },
    Instruction { opcode: 0x0c, fmt: "INC C",         exec: exec::inc::start,    stack: Vec::new() },
    Instruction { opcode: 0x0d, fmt: "DEC C",         exec: exec::dec::start,    stack: Vec::new() },
    Instruction { opcode: 0x0e, fmt: "LD C, d8",      exec: exec::ld::start,     stack: Vec::new() },
    Instruction { opcode: 0x0f, fmt: "RRCA",          exec: exec::rrca::start,   stack: Vec::new() },
    Instruction { opcode: 0x10, fmt: "STOP",          exec: exec::stop::start,   stack: Vec::new() },
    Instruction { opcode: 0x11, fmt: "LD DE, (d16)",  exec: exec::ldw::start,    stack: Vec::new() },
    Instruction { opcode: 0x12, fmt: "LD (DE), A",    exec: exec::ld::start,     stack: Vec::new() },
    Instruction { opcode: 0x13, fmt: "INC DE",        exec: exec::incw::start,   stack: Vec::new() },
    Instruction { opcode: 0x14, fmt: "INC D",         exec: exec::inc::start,    stack: Vec::new() },
    Instruction { opcode: 0x15, fmt: "DEC D",         exec: exec::dec::start,    stack: Vec::new() },
    Instruction { opcode: 0x16, fmt: "LD D, d8",      exec: exec::ld::start,     stack: Vec::new() },
    Instruction { opcode: 0x17, fmt: "RLA",           exec: exec::rla::start,    stack: Vec::new() },
    Instruction { opcode: 0x18, fmt: "JR r8",         exec: exec::jr::start,     stack: Vec::new() },
    Instruction { opcode: 0x19, fmt: "ADD HL, DE",    exec: exec::addw::start,   stack: Vec::new() },
    Instruction { opcode: 0x1a, fmt: "LD A, (DE)",    exec: exec::ld::start,     stack: Vec::new() },
    Instruction { opcode: 0x1b, fmt: "DEC DE",        exec: exec::decw::start,   stack: Vec::new() },
    Instruction { opcode: 0x1c, fmt: "INC E",         exec: exec::inc::start,    stack: Vec::new() },
    Instruction { opcode: 0x1d, fmt: "DEC E",         exec: exec::dec::start,    stack: Vec::new() },
    Instruction { opcode: 0x1e, fmt: "LD E, d8",      exec: exec::ld::start,     stack: Vec::new() },
    Instruction { opcode: 0x1f, fmt: "RRA",           exec: exec::rra::start,    stack: Vec::new() },
    Instruction { opcode: 0x20, fmt: "JR NZ, r8",     exec: exec::jr::start,     stack: Vec::new() },
    Instruction { opcode: 0x21, fmt: "LD HL, d16",    exec: exec::ldw::start,    stack: Vec::new() },
    Instruction { opcode: 0x22, fmt: "LD (HL+), A",   exec: exec::ld::start,     stack: Vec::new() },
    Instruction { opcode: 0x23, fmt: "INC HL",        exec: exec::incw::start,   stack: Vec::new() },
    Instruction { opcode: 0x24, fmt: "INC H",         exec: exec::inc::start,    stack: Vec::new() },
    Instruction { opcode: 0x25, fmt: "DEC H",         exec: exec::dec::start,    stack: Vec::new() },
    Instruction { opcode: 0x26, fmt: "LD H, d8",      exec: exec::ld::start,     stack: Vec::new() },
    Instruction { opcode: 0x27, fmt: "DAA",           exec: exec::daa::start,    stack: Vec::new() },
    Instruction { opcode: 0x28, fmt: "JR Z, r8",      exec: exec::jr::start,     stack: Vec::new() },
    Instruction { opcode: 0x29, fmt: "ADD HL, HL",    exec: exec::addw::start,   stack: Vec::new() },
    Instruction { opcode: 0x2a, fmt: "LD A, (HL+)",   exec: exec::ld::start,     stack: Vec::new() },
    Instruction { opcode: 0x2b, fmt: "DEC HL",        exec: exec::decw::start,   stack: Vec::new() },
    Instruction { opcode: 0x2c, fmt: "INC L",         exec: exec::inc::start,    stack: Vec::new() },
    Instruction { opcode: 0x2d, fmt: "DEC L",         exec: exec::dec::start,    stack: Vec::new() },
    Instruction { opcode: 0x2e, fmt: "LD L, d8",      exec: exec::ld::start,     stack: Vec::new() },
    Instruction { opcode: 0x2f, fmt: "CPL",           exec: exec::cpl::start,    stack: Vec::new() },
    Instruction { opcode: 0x30, fmt: "JR NC, r8",     exec: exec::jr::start,     stack: Vec::new() },
    Instruction { opcode: 0x31, fmt: "LD SP, d16",    exec: exec::ldw::start,    stack: Vec::new() },
    Instruction { opcode: 0x32, fmt: "LD (HL-), A",   exec: exec::ld::start,     stack: Vec::new() },
    Instruction { opcode: 0x33, fmt: "INC SP",        exec: exec::incw::start,   stack: Vec::new() },
    Instruction { opcode: 0x34, fmt: "INC (HL)",      exec: exec::inc::start,    stack: Vec::new() },
    Instruction { opcode: 0x35, fmt: "DEC (HL)",      exec: exec::dec::start,    stack: Vec::new() },
    Instruction { opcode: 0x36, fmt: "LD (HL), d8",   exec: exec::ld::start,     stack: Vec::new() },
    Instruction { opcode: 0x37, fmt: "SCF",           exec: exec::scf::start,    stack: Vec::new() },
    Instruction { opcode: 0x38, fmt: "JR C, r8",      exec: exec::jr::start,     stack: Vec::new() },
    Instruction { opcode: 0x39, fmt: "ADD HL, SP",    exec: exec::addw::start,   stack: Vec::new() },
    Instruction { opcode: 0x3a, fmt: "LD A, (HL-)",   exec: exec::ld::start,     stack: Vec::new() },
    Instruction { opcode: 0x3b, fmt: "DEC SP",        exec: exec::decw::start,   stack: Vec::new() },
    Instruction { opcode: 0x3c, fmt: "INC A",         exec: exec::inc::start,    stack: Vec::new() },
    Instruction { opcode: 0x3d, fmt: "DEC A",         exec: exec::dec::start,    stack: Vec::new() },
    Instruction { opcode: 0x3e, fmt: "LD A, d8",      exec: exec::ld::start,     stack: Vec::new() },
    Instruction { opcode: 0x3f, fmt: "CCP",           exec: exec::ccf::start,    stack: Vec::new() },
    Instruction { opcode: 0x40, fmt: "LD B, B",       exec: exec::ld::start,     stack: Vec::new() },
    Instruction { opcode: 0x41, fmt: "LD B, C",       exec: exec::ld::start,     stack: Vec::new() },
    Instruction { opcode: 0x42, fmt: "LD B, D",       exec: exec::ld::start,     stack: Vec::new() },
    Instruction { opcode: 0x43, fmt: "LD B, E",       exec: exec::ld::start,     stack: Vec::new() },
    Instruction { opcode: 0x44, fmt: "LD B, H",       exec: exec::ld::start,     stack: Vec::new() },
    Instruction { opcode: 0x45, fmt: "LD B, L",       exec: exec::ld::start,     stack: Vec::new() },
    Instruction { opcode: 0x46, fmt: "LD B, (HL)",    exec: exec::ld::start,     stack: Vec::new() },
    Instruction { opcode: 0x47, fmt: "LD B, A",       exec: exec::ld::start,     stack: Vec::new() },
    Instruction { opcode: 0x48, fmt: "LD C, B",       exec: exec::ld::start,     stack: Vec::new() },
    Instruction { opcode: 0x49, fmt: "LD C, C",       exec: exec::ld::start,     stack: Vec::new() },
    Instruction { opcode: 0x4a, fmt: "LD C, D",       exec: exec::ld::start,     stack: Vec::new() },
    Instruction { opcode: 0x4b, fmt: "LD C, E",       exec: exec::ld::start,     stack: Vec::new() },
    Instruction { opcode: 0x4c, fmt: "LD C, H",       exec: exec::ld::start,     stack: Vec::new() },
    Instruction { opcode: 0x4d, fmt: "LD C, L",       exec: exec::ld::start,     stack: Vec::new() },
    Instruction { opcode: 0x4e, fmt: "LD C, (HL)",    exec: exec::ld::start,     stack: Vec::new() },
    Instruction { opcode: 0x4f, fmt: "LD C, A",       exec: exec::ld::start,     stack: Vec::new() },
    Instruction { opcode: 0x50, fmt: "LD D, B",       exec: exec::ld::start,     stack: Vec::new() },
    Instruction { opcode: 0x51, fmt: "LD D, C",       exec: exec::ld::start,     stack: Vec::new() },
    Instruction { opcode: 0x52, fmt: "LD D, D",       exec: exec::ld::start,     stack: Vec::new() },
    Instruction { opcode: 0x53, fmt: "LD D, E",       exec: exec::ld::start,     stack: Vec::new() },
    Instruction { opcode: 0x54, fmt: "LD D, H",       exec: exec::ld::start,     stack: Vec::new() },
    Instruction { opcode: 0x55, fmt: "LD D, L",       exec: exec::ld::start,     stack: Vec::new() },
    Instruction { opcode: 0x56, fmt: "LD D, (HL)",    exec: exec::ld::start,     stack: Vec::new() },
    Instruction { opcode: 0x57, fmt: "LD D, A",       exec: exec::ld::start,     stack: Vec::new() },
    Instruction { opcode: 0x58, fmt: "LD E, B",       exec: exec::ld::start,     stack: Vec::new() },
    Instruction { opcode: 0x59, fmt: "LD E, C",       exec: exec::ld::start,     stack: Vec::new() },
    Instruction { opcode: 0x5a, fmt: "LD E, D",       exec: exec::ld::start,     stack: Vec::new() },
    Instruction { opcode: 0x5b, fmt: "LD E, E",       exec: exec::ld::start,     stack: Vec::new() },
    Instruction { opcode: 0x5c, fmt: "LD E, H",       exec: exec::ld::start,     stack: Vec::new() },
    Instruction { opcode: 0x5d, fmt: "LD E, L",       exec: exec::ld::start,     stack: Vec::new() },
    Instruction { opcode: 0x5e, fmt: "LD E, (HL)",    exec: exec::ld::start,     stack: Vec::new() },
    Instruction { opcode: 0x5f, fmt: "LD E, A",       exec: exec::ld::start,     stack: Vec::new() },
    Instruction { opcode: 0x60, fmt: "LD H, B",       exec: exec::ld::start,     stack: Vec::new() },
    Instruction { opcode: 0x61, fmt: "LD H, C",       exec: exec::ld::start,     stack: Vec::new() },
    Instruction { opcode: 0x62, fmt: "LD H, D",       exec: exec::ld::start,     stack: Vec::new() },
    Instruction { opcode: 0x63, fmt: "LD H, E",       exec: exec::ld::start,     stack: Vec::new() },
    Instruction { opcode: 0x64, fmt: "LD H, H",       exec: exec::ld::start,     stack: Vec::new() },
    Instruction { opcode: 0x65, fmt: "LD H, L",       exec: exec::ld::start,     stack: Vec::new() },
    Instruction { opcode: 0x66, fmt: "LD H, (HL)",    exec: exec::ld::start,     stack: Vec::new() },
    Instruction { opcode: 0x67, fmt: "LD H, A",       exec: exec::ld::start,     stack: Vec::new() },
    Instruction { opcode: 0x68, fmt: "LD L, B",       exec: exec::ld::start,     stack: Vec::new() },
    Instruction { opcode: 0x69, fmt: "LD L, C",       exec: exec::ld::start,     stack: Vec::new() },
    Instruction { opcode: 0x6a, fmt: "LD L, D",       exec: exec::ld::start,     stack: Vec::new() },
    Instruction { opcode: 0x6b, fmt: "LD L, E",       exec: exec::ld::start,     stack: Vec::new() },
    Instruction { opcode: 0x6c, fmt: "LD L, H",       exec: exec::ld::start,     stack: Vec::new() },
    Instruction { opcode: 0x6d, fmt: "LD L, L",       exec: exec::ld::start,     stack: Vec::new() },
    Instruction { opcode: 0x6e, fmt: "LD L, (HL)",    exec: exec::ld::start,     stack: Vec::new() },
    Instruction { opcode: 0x6f, fmt: "LD L, A",       exec: exec::ld::start,     stack: Vec::new() },
    Instruction { opcode: 0x70, fmt: "LD (HL), B",    exec: exec::ld::start,     stack: Vec::new() },
    Instruction { opcode: 0x71, fmt: "LD (HL), C",    exec: exec::ld::start,     stack: Vec::new() },
    Instruction { opcode: 0x72, fmt: "LD (HL), D",    exec: exec::ld::start,     stack: Vec::new() },
    Instruction { opcode: 0x73, fmt: "LD (HL), E",    exec: exec::ld::start,     stack: Vec::new() },
    Instruction { opcode: 0x74, fmt: "LD (HL), H",    exec: exec::ld::start,     stack: Vec::new() },
    Instruction { opcode: 0x75, fmt: "LD (HL), L",    exec: exec::ld::start,     stack: Vec::new() },
    Instruction { opcode: 0x76, fmt: "HALT",          exec: exec::halt::start,   stack: Vec::new() },
    Instruction { opcode: 0x77, fmt: "LD (HL), A",    exec: exec::ld::start,     stack: Vec::new() },
    Instruction { opcode: 0x78, fmt: "LD A, B",       exec: exec::ld::start,     stack: Vec::new() },
    Instruction { opcode: 0x79, fmt: "LD A, C",       exec: exec::ld::start,     stack: Vec::new() },
    Instruction { opcode: 0x7a, fmt: "LD A, D",       exec: exec::ld::start,     stack: Vec::new() },
    Instruction { opcode: 0x7b, fmt: "LD A, E",       exec: exec::ld::start,     stack: Vec::new() },
    Instruction { opcode: 0x7c, fmt: "LD A, H",       exec: exec::ld::start,     stack: Vec::new() },
    Instruction { opcode: 0x7d, fmt: "LD A, L",       exec: exec::ld::start,     stack: Vec::new() },
    Instruction { opcode: 0x7e, fmt: "LD A, (HL)",    exec: exec::ld::start,     stack: Vec::new() },
    Instruction { opcode: 0x7f, fmt: "LD A, A",       exec: exec::ld::start,     stack: Vec::new() },
    Instruction { opcode: 0x80, fmt: "ADD A, B",      exec: exec::add::start,    stack: Vec::new() },
    Instruction { opcode: 0x81, fmt: "ADD A, C",      exec: exec::add::start,    stack: Vec::new() },
    Instruction { opcode: 0x82, fmt: "ADD A, D",      exec: exec::add::start,    stack: Vec::new() },
    Instruction { opcode: 0x83, fmt: "ADD A, E",      exec: exec::add::start,    stack: Vec::new() },
    Instruction { opcode: 0x84, fmt: "ADD A, H",      exec: exec::add::start,    stack: Vec::new() },
    Instruction { opcode: 0x85, fmt: "ADD A, L",      exec: exec::add::start,    stack: Vec::new() },
    Instruction { opcode: 0x86, fmt: "ADD A, (HL)",   exec: exec::add::start,    stack: Vec::new() },
    Instruction { opcode: 0x87, fmt: "ADD A, A",      exec: exec::add::start,    stack: Vec::new() },
    Instruction { opcode: 0x88, fmt: "ADC A, B",      exec: exec::adc::start,    stack: Vec::new() },
    Instruction { opcode: 0x89, fmt: "ADC A, C",      exec: exec::adc::start,    stack: Vec::new() },
    Instruction { opcode: 0x8a, fmt: "ADC A, D",      exec: exec::adc::start,    stack: Vec::new() },
    Instruction { opcode: 0x8b, fmt: "ADC A, E",      exec: exec::adc::start,    stack: Vec::new() },
    Instruction { opcode: 0x8c, fmt: "ADC A, H",      exec: exec::adc::start,    stack: Vec::new() },
    Instruction { opcode: 0x8d, fmt: "ADC A, L",      exec: exec::adc::start,    stack: Vec::new() },
    Instruction { opcode: 0x8e, fmt: "ADC A, (HL)",   exec: exec::adc::start,    stack: Vec::new() },
    Instruction { opcode: 0x8f, fmt: "ADC A, A",      exec: exec::adc::start,    stack: Vec::new() },
    Instruction { opcode: 0x90, fmt: "SUB A, B",      exec: exec::sub::start,    stack: Vec::new() },
    Instruction { opcode: 0x91, fmt: "SUB A, C",      exec: exec::sub::start,    stack: Vec::new() },
    Instruction { opcode: 0x92, fmt: "SUB A, D",      exec: exec::sub::start,    stack: Vec::new() },
    Instruction { opcode: 0x93, fmt: "SUB A, E",      exec: exec::sub::start,    stack: Vec::new() },
    Instruction { opcode: 0x94, fmt: "SUB A, H",      exec: exec::sub::start,    stack: Vec::new() },
    Instruction { opcode: 0x95, fmt: "SUB A, L",      exec: exec::sub::start,    stack: Vec::new() },
    Instruction { opcode: 0x96, fmt: "SUB A, (HL)",   exec: exec::sub::start,    stack: Vec::new() },
    Instruction { opcode: 0x97, fmt: "SUB A, A",      exec: exec::sub::start,    stack: Vec::new() },
    Instruction { opcode: 0x98, fmt: "SBC A, B",      exec: exec::sbc::start,    stack: Vec::new() },
    Instruction { opcode: 0x99, fmt: "SBC A, C",      exec: exec::sbc::start,    stack: Vec::new() },
    Instruction { opcode: 0x9a, fmt: "SBC A, D",      exec: exec::sbc::start,    stack: Vec::new() },
    Instruction { opcode: 0x9b, fmt: "SBC A, E",      exec: exec::sbc::start,    stack: Vec::new() },
    Instruction { opcode: 0x9c, fmt: "SBC A, H",      exec: exec::sbc::start,    stack: Vec::new() },
    Instruction { opcode: 0x9d, fmt: "SBC A, L",      exec: exec::sbc::start,    stack: Vec::new() },
    Instruction { opcode: 0x9e, fmt: "SBC A, (HL)",   exec: exec::sbc::start,    stack: Vec::new() },
    Instruction { opcode: 0x9f, fmt: "SBC A, A",      exec: exec::sbc::start,    stack: Vec::new() },
    Instruction { opcode: 0xa0, fmt: "AND B",         exec: exec::and::start,    stack: Vec::new() },
    Instruction { opcode: 0xa1, fmt: "AND C",         exec: exec::and::start,    stack: Vec::new() },
    Instruction { opcode: 0xa2, fmt: "AND D",         exec: exec::and::start,    stack: Vec::new() },
    Instruction { opcode: 0xa3, fmt: "AND E",         exec: exec::and::start,    stack: Vec::new() },
    Instruction { opcode: 0xa4, fmt: "AND H",         exec: exec::and::start,    stack: Vec::new() },
    Instruction { opcode: 0xa5, fmt: "AND L",         exec: exec::and::start,    stack: Vec::new() },
    Instruction { opcode: 0xa6, fmt: "AND (HL)",      exec: exec::and::start,    stack: Vec::new() },
    Instruction { opcode: 0xa7, fmt: "AND A",         exec: exec::and::start,    stack: Vec::new() },
    Instruction { opcode: 0xa8, fmt: "XOR B",         exec: exec::xor::start,    stack: Vec::new() },
    Instruction { opcode: 0xa9, fmt: "XOR C",         exec: exec::xor::start,    stack: Vec::new() },
    Instruction { opcode: 0xaa, fmt: "XOR D",         exec: exec::xor::start,    stack: Vec::new() },
    Instruction { opcode: 0xab, fmt: "XOR E",         exec: exec::xor::start,    stack: Vec::new() },
    Instruction { opcode: 0xac, fmt: "XOR H",         exec: exec::xor::start,    stack: Vec::new() },
    Instruction { opcode: 0xad, fmt: "XOR L",         exec: exec::xor::start,    stack: Vec::new() },
    Instruction { opcode: 0xae, fmt: "XOR (HL)",      exec: exec::xor::start,    stack: Vec::new() },
    Instruction { opcode: 0xaf, fmt: "XOR A",         exec: exec::xor::start,    stack: Vec::new() },
    Instruction { opcode: 0xb0, fmt: "OR B",          exec: exec::or::start,     stack: Vec::new() },
    Instruction { opcode: 0xb1, fmt: "OR C",          exec: exec::or::start,     stack: Vec::new() },
    Instruction { opcode: 0xb2, fmt: "OR D",          exec: exec::or::start,     stack: Vec::new() },
    Instruction { opcode: 0xb3, fmt: "OR E",          exec: exec::or::start,     stack: Vec::new() },
    Instruction { opcode: 0xb4, fmt: "OR H",          exec: exec::or::start,     stack: Vec::new() },
    Instruction { opcode: 0xb5, fmt: "OR L",          exec: exec::or::start,     stack: Vec::new() },
    Instruction { opcode: 0xb6, fmt: "OR (HL)",       exec: exec::or::start,     stack: Vec::new() },
    Instruction { opcode: 0xb7, fmt: "OR A",          exec: exec::or::start,     stack: Vec::new() },
    Instruction { opcode: 0xb8, fmt: "CP B",          exec: exec::cp::start,     stack: Vec::new() },
    Instruction { opcode: 0xb9, fmt: "CP C",          exec: exec::cp::start,     stack: Vec::new() },
    Instruction { opcode: 0xba, fmt: "CP D",          exec: exec::cp::start,     stack: Vec::new() },
    Instruction { opcode: 0xbb, fmt: "CP E",          exec: exec::cp::start,     stack: Vec::new() },
    Instruction { opcode: 0xbc, fmt: "CP H",          exec: exec::cp::start,     stack: Vec::new() },
    Instruction { opcode: 0xbd, fmt: "CP L",          exec: exec::cp::start,     stack: Vec::new() },
    Instruction { opcode: 0xbe, fmt: "CP (HL)",       exec: exec::cp::start,     stack: Vec::new() },
    Instruction { opcode: 0xbf, fmt: "CP A",          exec: exec::cp::start,     stack: Vec::new() },
    Instruction { opcode: 0xc0, fmt: "RET NZ",        exec: exec::ret::start,    stack: Vec::new() },
    Instruction { opcode: 0xc1, fmt: "POP BC",        exec: exec::pop::start,    stack: Vec::new() },
    Instruction { opcode: 0xc2, fmt: "JP NZ, a16",    exec: exec::jp::start,     stack: Vec::new() },
    Instruction { opcode: 0xc3, fmt: "JP a16",        exec: exec::jp::start,     stack: Vec::new() },
    Instruction { opcode: 0xc4, fmt: "CALL NZ, a16",  exec: exec::call::start,   stack: Vec::new() },
    Instruction { opcode: 0xc5, fmt: "PUSH BC",       exec: exec::push::start,   stack: Vec::new() },
    Instruction { opcode: 0xc6, fmt: "ADD A, d8",     exec: exec::add::start,    stack: Vec::new() },
    Instruction { opcode: 0xc7, fmt: "RST 00H",       exec: exec::rst::start,    stack: Vec::new() },
    Instruction { opcode: 0xc8, fmt: "RET Z",         exec: exec::ret::start,    stack: Vec::new() },
    Instruction { opcode: 0xc9, fmt: "RET",           exec: exec::ret::start,    stack: Vec::new() },
    Instruction { opcode: 0xca, fmt: "JP Z, a16",     exec: exec::jp::start,     stack: Vec::new() },
    Instruction { opcode: 0xcb, fmt: "PREFIX",        exec: exec::prefix::start, stack: Vec::new() },
    Instruction { opcode: 0xcc, fmt: "CALL Z, a16",   exec: exec::call::start,   stack: Vec::new() },
    Instruction { opcode: 0xcd, fmt: "CALL a16",      exec: exec::call::start,   stack: Vec::new() },
    Instruction { opcode: 0xce, fmt: "ADC A, d8",     exec: exec::adc::start,    stack: Vec::new() },
    Instruction { opcode: 0xcf, fmt: "RST 08H",       exec: exec::rst::start,    stack: Vec::new() },
    Instruction { opcode: 0xd0, fmt: "RET NC",        exec: exec::ret::start,    stack: Vec::new() },
    Instruction { opcode: 0xd1, fmt: "POP DE",        exec: exec::pop::start,    stack: Vec::new() },
    Instruction { opcode: 0xd2, fmt: "JP NC, a16",    exec: exec::jp::start,     stack: Vec::new() },
    Instruction { opcode: 0xd3, fmt: "UNUSED",        exec: exec::unused::start, stack: Vec::new() },
    Instruction { opcode: 0xd4, fmt: "CALL NC, a16",  exec: exec::call::start,   stack: Vec::new() },
    Instruction { opcode: 0xd5, fmt: "PUSH DE",       exec: exec::push::start,   stack: Vec::new() },
    Instruction { opcode: 0xd6, fmt: "SUB d8",        exec: exec::sub::start,    stack: Vec::new() },
    Instruction { opcode: 0xd7, fmt: "RST 10H",       exec: exec::rst::start,    stack: Vec::new() },
    Instruction { opcode: 0xd8, fmt: "RET C",         exec: exec::ret::start,    stack: Vec::new() },
    Instruction { opcode: 0xd9, fmt: "RETI",          exec: exec::reti::start,   stack: Vec::new() },
    Instruction { opcode: 0xda, fmt: "JP C, a16",     exec: exec::jp::start,     stack: Vec::new() },
    Instruction { opcode: 0xdb, fmt: "UNUSED",        exec: exec::unused::start, stack: Vec::new() },
    Instruction { opcode: 0xdc, fmt: "CALL C, a16",   exec: exec::call::start,   stack: Vec::new() },
    Instruction { opcode: 0xdd, fmt: "UNUSED",        exec: exec::unused::start, stack: Vec::new() },
    Instruction { opcode: 0xde, fmt: "SBC A, d8",     exec: exec::sbc::start,    stack: Vec::new() },
    Instruction { opcode: 0xdf, fmt: "RST 18H",       exec: exec::rst::start,    stack: Vec::new() },
    Instruction { opcode: 0xe0, fmt: "LDH (a8), A",   exec: exec::ldh::start,    stack: Vec::new() },
    Instruction { opcode: 0xe1, fmt: "POP HL",        exec: exec::pop::start,    stack: Vec::new() },
    Instruction { opcode: 0xe2, fmt: "LDH (C), A",    exec: exec::ldh::start,    stack: Vec::new() },
    Instruction { opcode: 0xe3, fmt: "UNUSED",        exec: exec::unused::start, stack: Vec::new() },
    Instruction { opcode: 0xe4, fmt: "UNUSED",        exec: exec::unused::start, stack: Vec::new() },
    Instruction { opcode: 0xe5, fmt: "PUSH HL",       exec: exec::push::start,   stack: Vec::new() },
    Instruction { opcode: 0xe6, fmt: "AND d8",        exec: exec::and::start,    stack: Vec::new() },
    Instruction { opcode: 0xe7, fmt: "RST 20H",       exec: exec::rst::start,    stack: Vec::new() },
    Instruction { opcode: 0xe8, fmt: "ADD SP, r8",    exec: exec::addw::start,   stack: Vec::new() },
    Instruction { opcode: 0xe9, fmt: "JP HL",         exec: exec::jp::start,     stack: Vec::new() },
    Instruction { opcode: 0xea, fmt: "LD (a16), A",   exec: exec::ld::start,     stack: Vec::new() },
    Instruction { opcode: 0xeb, fmt: "UNUSED",        exec: exec::unused::start, stack: Vec::new() },
    Instruction { opcode: 0xec, fmt: "UNUSED",        exec: exec::unused::start, stack: Vec::new() },
    Instruction { opcode: 0xed, fmt: "UNUSED",        exec: exec::unused::start, stack: Vec::new() },
    Instruction { opcode: 0xee, fmt: "XOR d8",        exec: exec::xor::start,    stack: Vec::new() },
    Instruction { opcode: 0xef, fmt: "RST 28H",       exec: exec::rst::start,    stack: Vec::new() },
    Instruction { opcode: 0xf0, fmt: "LDH A, (a8)",   exec: exec::ldh::start,    stack: Vec::new() },
    Instruction { opcode: 0xf1, fmt: "POP AF",        exec: exec::pop::start,    stack: Vec::new() },
    Instruction { opcode: 0xf2, fmt: "LD A, (C)",     exec: exec::ldh::start,    stack: Vec::new() },
    Instruction { opcode: 0xf3, fmt: "DI",            exec: exec::di::start,     stack: Vec::new() },
    Instruction { opcode: 0xf4, fmt: "UNUSED",        exec: exec::unused::start, stack: Vec::new() },
    Instruction { opcode: 0xf5, fmt: "PUSH AF",       exec: exec::push::start,   stack: Vec::new() },
    Instruction { opcode: 0xf6, fmt: "OR d8",         exec: exec::or::start,     stack: Vec::new() },
    Instruction { opcode: 0xf7, fmt: "RST 30H",       exec: exec::rst::start,    stack: Vec::new() },
    Instruction { opcode: 0xf8, fmt: "LD HL, SP + r8",exec: exec::ldw::start,    stack: Vec::new() },
    Instruction { opcode: 0xf9, fmt: "LD SP, HL",     exec: exec::ldw::start,    stack: Vec::new() },
    Instruction { opcode: 0xfa, fmt: "LD A, (a16)",   exec: exec::ld::start,     stack: Vec::new() },
    Instruction { opcode: 0xfb, fmt: "EI",            exec: exec::ei::start,     stack: Vec::new() },
    Instruction { opcode: 0xfc, fmt: "UNUSED",        exec: exec::unused::start, stack: Vec::new() },
    Instruction { opcode: 0xfd, fmt: "UNUSED",        exec: exec::unused::start, stack: Vec::new() },
    Instruction { opcode: 0xfe, fmt: "CP d8",         exec: exec::cp::start,     stack: Vec::new() },
    Instruction { opcode: 0xff, fmt: "RST 38H",       exec: exec::rst::start,    stack: Vec::new() },
];

/// Prefix lookup table.
#[rustfmt::skip]
const PREFIX: [Instruction; 0x100] = [
    Instruction { opcode: 0x00, fmt: "RLC B",         exec: exec::rlc::start,    stack: Vec::new() },
    Instruction { opcode: 0x01, fmt: "RLC C",         exec: exec::rlc::start,    stack: Vec::new() },
    Instruction { opcode: 0x02, fmt: "RLC D",         exec: exec::rlc::start,    stack: Vec::new() },
    Instruction { opcode: 0x03, fmt: "RLC E",         exec: exec::rlc::start,    stack: Vec::new() },
    Instruction { opcode: 0x04, fmt: "RLC H",         exec: exec::rlc::start,    stack: Vec::new() },
    Instruction { opcode: 0x05, fmt: "RLC L",         exec: exec::rlc::start,    stack: Vec::new() },
    Instruction { opcode: 0x06, fmt: "RLC (HL)",      exec: exec::rlc::start,    stack: Vec::new() },
    Instruction { opcode: 0x07, fmt: "RLC A",         exec: exec::rlc::start,    stack: Vec::new() },
    Instruction { opcode: 0x08, fmt: "RRC B",         exec: exec::rrc::start,    stack: Vec::new() },
    Instruction { opcode: 0x09, fmt: "RRC C",         exec: exec::rrc::start,    stack: Vec::new() },
    Instruction { opcode: 0x0a, fmt: "RRC D",         exec: exec::rrc::start,    stack: Vec::new() },
    Instruction { opcode: 0x0b, fmt: "RRC E",         exec: exec::rrc::start,    stack: Vec::new() },
    Instruction { opcode: 0x0c, fmt: "RRC H",         exec: exec::rrc::start,    stack: Vec::new() },
    Instruction { opcode: 0x0d, fmt: "RRC L",         exec: exec::rrc::start,    stack: Vec::new() },
    Instruction { opcode: 0x0e, fmt: "RRC (HL)",      exec: exec::rrc::start,    stack: Vec::new() },
    Instruction { opcode: 0x0f, fmt: "RRC A",         exec: exec::rrc::start,    stack: Vec::new() },
    Instruction { opcode: 0x10, fmt: "RL B",          exec: exec::rl::start,     stack: Vec::new() },
    Instruction { opcode: 0x11, fmt: "RL C",          exec: exec::rl::start,     stack: Vec::new() },
    Instruction { opcode: 0x12, fmt: "RL D",          exec: exec::rl::start,     stack: Vec::new() },
    Instruction { opcode: 0x13, fmt: "RL E",          exec: exec::rl::start,     stack: Vec::new() },
    Instruction { opcode: 0x14, fmt: "RL H",          exec: exec::rl::start,     stack: Vec::new() },
    Instruction { opcode: 0x15, fmt: "RL L",          exec: exec::rl::start,     stack: Vec::new() },
    Instruction { opcode: 0x16, fmt: "RL (HL)",       exec: exec::rl::start,     stack: Vec::new() },
    Instruction { opcode: 0x17, fmt: "RL A",          exec: exec::rl::start,     stack: Vec::new() },
    Instruction { opcode: 0x18, fmt: "RR B",          exec: exec::rr::start,     stack: Vec::new() },
    Instruction { opcode: 0x19, fmt: "RR C",          exec: exec::rr::start,     stack: Vec::new() },
    Instruction { opcode: 0x1a, fmt: "RR D",          exec: exec::rr::start,     stack: Vec::new() },
    Instruction { opcode: 0x1b, fmt: "RR E",          exec: exec::rr::start,     stack: Vec::new() },
    Instruction { opcode: 0x1c, fmt: "RR H",          exec: exec::rr::start,     stack: Vec::new() },
    Instruction { opcode: 0x1d, fmt: "RR L",          exec: exec::rr::start,     stack: Vec::new() },
    Instruction { opcode: 0x1e, fmt: "RR (HL)",       exec: exec::rr::start,     stack: Vec::new() },
    Instruction { opcode: 0x1f, fmt: "RR A",          exec: exec::rr::start,     stack: Vec::new() },
    Instruction { opcode: 0x20, fmt: "SLA B",         exec: exec::sla::start,    stack: Vec::new() },
    Instruction { opcode: 0x21, fmt: "SLA C",         exec: exec::sla::start,    stack: Vec::new() },
    Instruction { opcode: 0x22, fmt: "SLA D",         exec: exec::sla::start,    stack: Vec::new() },
    Instruction { opcode: 0x23, fmt: "SLA E",         exec: exec::sla::start,    stack: Vec::new() },
    Instruction { opcode: 0x24, fmt: "SLA H",         exec: exec::sla::start,    stack: Vec::new() },
    Instruction { opcode: 0x25, fmt: "SLA L",         exec: exec::sla::start,    stack: Vec::new() },
    Instruction { opcode: 0x26, fmt: "SLA (HL)",      exec: exec::sla::start,    stack: Vec::new() },
    Instruction { opcode: 0x27, fmt: "SLA A",         exec: exec::sla::start,    stack: Vec::new() },
    Instruction { opcode: 0x28, fmt: "SRA B",         exec: exec::sra::start,    stack: Vec::new() },
    Instruction { opcode: 0x29, fmt: "SRA C",         exec: exec::sra::start,    stack: Vec::new() },
    Instruction { opcode: 0x2a, fmt: "SRA D",         exec: exec::sra::start,    stack: Vec::new() },
    Instruction { opcode: 0x2b, fmt: "SRA E",         exec: exec::sra::start,    stack: Vec::new() },
    Instruction { opcode: 0x2c, fmt: "SRA H",         exec: exec::sra::start,    stack: Vec::new() },
    Instruction { opcode: 0x2d, fmt: "SRA L",         exec: exec::sra::start,    stack: Vec::new() },
    Instruction { opcode: 0x2e, fmt: "SRA (HL)",      exec: exec::sra::start,    stack: Vec::new() },
    Instruction { opcode: 0x2f, fmt: "SRA A",         exec: exec::sra::start,    stack: Vec::new() },
    Instruction { opcode: 0x30, fmt: "SWAP B",        exec: exec::swap::start,   stack: Vec::new() },
    Instruction { opcode: 0x31, fmt: "SWAP C",        exec: exec::swap::start,   stack: Vec::new() },
    Instruction { opcode: 0x32, fmt: "SWAP D",        exec: exec::swap::start,   stack: Vec::new() },
    Instruction { opcode: 0x33, fmt: "SWAP E",        exec: exec::swap::start,   stack: Vec::new() },
    Instruction { opcode: 0x34, fmt: "SWAP H",        exec: exec::swap::start,   stack: Vec::new() },
    Instruction { opcode: 0x35, fmt: "SWAP L",        exec: exec::swap::start,   stack: Vec::new() },
    Instruction { opcode: 0x36, fmt: "SWAP (HL)",     exec: exec::swap::start,   stack: Vec::new() },
    Instruction { opcode: 0x37, fmt: "SWAP A",        exec: exec::swap::start,   stack: Vec::new() },
    Instruction { opcode: 0x38, fmt: "SRL B",         exec: exec::srl::start,    stack: Vec::new() },
    Instruction { opcode: 0x39, fmt: "SRL C",         exec: exec::srl::start,    stack: Vec::new() },
    Instruction { opcode: 0x3a, fmt: "SRL D",         exec: exec::srl::start,    stack: Vec::new() },
    Instruction { opcode: 0x3b, fmt: "SRL E",         exec: exec::srl::start,    stack: Vec::new() },
    Instruction { opcode: 0x3c, fmt: "SRL H",         exec: exec::srl::start,    stack: Vec::new() },
    Instruction { opcode: 0x3d, fmt: "SRL L",         exec: exec::srl::start,    stack: Vec::new() },
    Instruction { opcode: 0x3e, fmt: "SRL (HL)",      exec: exec::srl::start,    stack: Vec::new() },
    Instruction { opcode: 0x3f, fmt: "SRL A",         exec: exec::srl::start,    stack: Vec::new() },
    Instruction { opcode: 0x40, fmt: "BIT 0, B",      exec: exec::bit::start,    stack: Vec::new() },
    Instruction { opcode: 0x41, fmt: "BIT 0, C",      exec: exec::bit::start,    stack: Vec::new() },
    Instruction { opcode: 0x42, fmt: "BIT 0, D",      exec: exec::bit::start,    stack: Vec::new() },
    Instruction { opcode: 0x43, fmt: "BIT 0, E",      exec: exec::bit::start,    stack: Vec::new() },
    Instruction { opcode: 0x44, fmt: "BIT 0, H",      exec: exec::bit::start,    stack: Vec::new() },
    Instruction { opcode: 0x45, fmt: "BIT 0, L",      exec: exec::bit::start,    stack: Vec::new() },
    Instruction { opcode: 0x46, fmt: "BIT 0, (HL)",   exec: exec::bit::start,    stack: Vec::new() },
    Instruction { opcode: 0x47, fmt: "BIT 0, A",      exec: exec::bit::start,    stack: Vec::new() },
    Instruction { opcode: 0x48, fmt: "BIT 1, B",      exec: exec::bit::start,    stack: Vec::new() },
    Instruction { opcode: 0x49, fmt: "BIT 1, C",      exec: exec::bit::start,    stack: Vec::new() },
    Instruction { opcode: 0x4a, fmt: "BIT 1, D",      exec: exec::bit::start,    stack: Vec::new() },
    Instruction { opcode: 0x4b, fmt: "BIT 1, E",      exec: exec::bit::start,    stack: Vec::new() },
    Instruction { opcode: 0x4c, fmt: "BIT 1, H",      exec: exec::bit::start,    stack: Vec::new() },
    Instruction { opcode: 0x4d, fmt: "BIT 1, L",      exec: exec::bit::start,    stack: Vec::new() },
    Instruction { opcode: 0x4e, fmt: "BIT 1, (HL)",   exec: exec::bit::start,    stack: Vec::new() },
    Instruction { opcode: 0x4f, fmt: "BIT 1, A",      exec: exec::bit::start,    stack: Vec::new() },
    Instruction { opcode: 0x50, fmt: "BIT 2, B",      exec: exec::bit::start,    stack: Vec::new() },
    Instruction { opcode: 0x51, fmt: "BIT 2, C",      exec: exec::bit::start,    stack: Vec::new() },
    Instruction { opcode: 0x52, fmt: "BIT 2, D",      exec: exec::bit::start,    stack: Vec::new() },
    Instruction { opcode: 0x53, fmt: "BIT 2, E",      exec: exec::bit::start,    stack: Vec::new() },
    Instruction { opcode: 0x54, fmt: "BIT 2, H",      exec: exec::bit::start,    stack: Vec::new() },
    Instruction { opcode: 0x55, fmt: "BIT 2, L",      exec: exec::bit::start,    stack: Vec::new() },
    Instruction { opcode: 0x56, fmt: "BIT 2, (HL)",   exec: exec::bit::start,    stack: Vec::new() },
    Instruction { opcode: 0x57, fmt: "BIT 2, A",      exec: exec::bit::start,    stack: Vec::new() },
    Instruction { opcode: 0x58, fmt: "BIT 3, B",      exec: exec::bit::start,    stack: Vec::new() },
    Instruction { opcode: 0x59, fmt: "BIT 3, C",      exec: exec::bit::start,    stack: Vec::new() },
    Instruction { opcode: 0x5a, fmt: "BIT 3, D",      exec: exec::bit::start,    stack: Vec::new() },
    Instruction { opcode: 0x5b, fmt: "BIT 3, E",      exec: exec::bit::start,    stack: Vec::new() },
    Instruction { opcode: 0x5c, fmt: "BIT 3, H",      exec: exec::bit::start,    stack: Vec::new() },
    Instruction { opcode: 0x5d, fmt: "BIT 3, L",      exec: exec::bit::start,    stack: Vec::new() },
    Instruction { opcode: 0x5e, fmt: "BIT 3, (HL)",   exec: exec::bit::start,    stack: Vec::new() },
    Instruction { opcode: 0x5f, fmt: "BIT 3, A",      exec: exec::bit::start,    stack: Vec::new() },
    Instruction { opcode: 0x60, fmt: "BIT 4, B",      exec: exec::bit::start,    stack: Vec::new() },
    Instruction { opcode: 0x61, fmt: "BIT 4, C",      exec: exec::bit::start,    stack: Vec::new() },
    Instruction { opcode: 0x62, fmt: "BIT 4, D",      exec: exec::bit::start,    stack: Vec::new() },
    Instruction { opcode: 0x63, fmt: "BIT 4, E",      exec: exec::bit::start,    stack: Vec::new() },
    Instruction { opcode: 0x64, fmt: "BIT 4, H",      exec: exec::bit::start,    stack: Vec::new() },
    Instruction { opcode: 0x65, fmt: "BIT 4, L",      exec: exec::bit::start,    stack: Vec::new() },
    Instruction { opcode: 0x66, fmt: "BIT 4, (HL)",   exec: exec::bit::start,    stack: Vec::new() },
    Instruction { opcode: 0x67, fmt: "BIT 4, A",      exec: exec::bit::start,    stack: Vec::new() },
    Instruction { opcode: 0x68, fmt: "BIT 5, B",      exec: exec::bit::start,    stack: Vec::new() },
    Instruction { opcode: 0x69, fmt: "BIT 5, C",      exec: exec::bit::start,    stack: Vec::new() },
    Instruction { opcode: 0x6a, fmt: "BIT 5, D",      exec: exec::bit::start,    stack: Vec::new() },
    Instruction { opcode: 0x6b, fmt: "BIT 5, E",      exec: exec::bit::start,    stack: Vec::new() },
    Instruction { opcode: 0x6c, fmt: "BIT 5, H",      exec: exec::bit::start,    stack: Vec::new() },
    Instruction { opcode: 0x6d, fmt: "BIT 5, L",      exec: exec::bit::start,    stack: Vec::new() },
    Instruction { opcode: 0x6e, fmt: "BIT 5, (HL)",   exec: exec::bit::start,    stack: Vec::new() },
    Instruction { opcode: 0x6f, fmt: "BIT 5, A",      exec: exec::bit::start,    stack: Vec::new() },
    Instruction { opcode: 0x70, fmt: "BIT 6, B",      exec: exec::bit::start,    stack: Vec::new() },
    Instruction { opcode: 0x71, fmt: "BIT 6, C",      exec: exec::bit::start,    stack: Vec::new() },
    Instruction { opcode: 0x72, fmt: "BIT 6, D",      exec: exec::bit::start,    stack: Vec::new() },
    Instruction { opcode: 0x73, fmt: "BIT 6, E",      exec: exec::bit::start,    stack: Vec::new() },
    Instruction { opcode: 0x74, fmt: "BIT 6, H",      exec: exec::bit::start,    stack: Vec::new() },
    Instruction { opcode: 0x75, fmt: "BIT 6, L",      exec: exec::bit::start,    stack: Vec::new() },
    Instruction { opcode: 0x76, fmt: "BIT 6, (HL)",   exec: exec::bit::start,    stack: Vec::new() },
    Instruction { opcode: 0x77, fmt: "BIT 6, A",      exec: exec::bit::start,    stack: Vec::new() },
    Instruction { opcode: 0x78, fmt: "BIT 7, B",      exec: exec::bit::start,    stack: Vec::new() },
    Instruction { opcode: 0x79, fmt: "BIT 7, C",      exec: exec::bit::start,    stack: Vec::new() },
    Instruction { opcode: 0x7a, fmt: "BIT 7, D",      exec: exec::bit::start,    stack: Vec::new() },
    Instruction { opcode: 0x7b, fmt: "BIT 7, E",      exec: exec::bit::start,    stack: Vec::new() },
    Instruction { opcode: 0x7c, fmt: "BIT 7, H",      exec: exec::bit::start,    stack: Vec::new() },
    Instruction { opcode: 0x7d, fmt: "BIT 7, L",      exec: exec::bit::start,    stack: Vec::new() },
    Instruction { opcode: 0x7e, fmt: "BIT 7, (HL)",   exec: exec::bit::start,    stack: Vec::new() },
    Instruction { opcode: 0x7f, fmt: "BIT 7, A",      exec: exec::bit::start,    stack: Vec::new() },
    Instruction { opcode: 0x80, fmt: "RES 0, B",      exec: exec::res::start,    stack: Vec::new() },
    Instruction { opcode: 0x81, fmt: "RES 0, C",      exec: exec::res::start,    stack: Vec::new() },
    Instruction { opcode: 0x82, fmt: "RES 0, D",      exec: exec::res::start,    stack: Vec::new() },
    Instruction { opcode: 0x83, fmt: "RES 0, E",      exec: exec::res::start,    stack: Vec::new() },
    Instruction { opcode: 0x84, fmt: "RES 0, H",      exec: exec::res::start,    stack: Vec::new() },
    Instruction { opcode: 0x85, fmt: "RES 0, L",      exec: exec::res::start,    stack: Vec::new() },
    Instruction { opcode: 0x86, fmt: "RES 0, (HL)",   exec: exec::res::start,    stack: Vec::new() },
    Instruction { opcode: 0x87, fmt: "RES 0, A",      exec: exec::res::start,    stack: Vec::new() },
    Instruction { opcode: 0x88, fmt: "RES 1, B",      exec: exec::res::start,    stack: Vec::new() },
    Instruction { opcode: 0x89, fmt: "RES 1, C",      exec: exec::res::start,    stack: Vec::new() },
    Instruction { opcode: 0x8a, fmt: "RES 1, D",      exec: exec::res::start,    stack: Vec::new() },
    Instruction { opcode: 0x8b, fmt: "RES 1, E",      exec: exec::res::start,    stack: Vec::new() },
    Instruction { opcode: 0x8c, fmt: "RES 1, H",      exec: exec::res::start,    stack: Vec::new() },
    Instruction { opcode: 0x8d, fmt: "RES 1, L",      exec: exec::res::start,    stack: Vec::new() },
    Instruction { opcode: 0x8e, fmt: "RES 1, (HL)",   exec: exec::res::start,    stack: Vec::new() },
    Instruction { opcode: 0x8f, fmt: "RES 1, A",      exec: exec::res::start,    stack: Vec::new() },
    Instruction { opcode: 0x90, fmt: "RES 2, B",      exec: exec::res::start,    stack: Vec::new() },
    Instruction { opcode: 0x91, fmt: "RES 2, C",      exec: exec::res::start,    stack: Vec::new() },
    Instruction { opcode: 0x92, fmt: "RES 2, D",      exec: exec::res::start,    stack: Vec::new() },
    Instruction { opcode: 0x93, fmt: "RES 2, E",      exec: exec::res::start,    stack: Vec::new() },
    Instruction { opcode: 0x94, fmt: "RES 2, H",      exec: exec::res::start,    stack: Vec::new() },
    Instruction { opcode: 0x95, fmt: "RES 2, L",      exec: exec::res::start,    stack: Vec::new() },
    Instruction { opcode: 0x96, fmt: "RES 2, (HL)",   exec: exec::res::start,    stack: Vec::new() },
    Instruction { opcode: 0x97, fmt: "RES 2, A",      exec: exec::res::start,    stack: Vec::new() },
    Instruction { opcode: 0x98, fmt: "RES 3, B",      exec: exec::res::start,    stack: Vec::new() },
    Instruction { opcode: 0x99, fmt: "RES 3, C",      exec: exec::res::start,    stack: Vec::new() },
    Instruction { opcode: 0x9a, fmt: "RES 3, D",      exec: exec::res::start,    stack: Vec::new() },
    Instruction { opcode: 0x9b, fmt: "RES 3, E",      exec: exec::res::start,    stack: Vec::new() },
    Instruction { opcode: 0x9c, fmt: "RES 3, H",      exec: exec::res::start,    stack: Vec::new() },
    Instruction { opcode: 0x9d, fmt: "RES 3, L",      exec: exec::res::start,    stack: Vec::new() },
    Instruction { opcode: 0x9e, fmt: "RES 3, (HL)",   exec: exec::res::start,    stack: Vec::new() },
    Instruction { opcode: 0x9f, fmt: "RES 3, A",      exec: exec::res::start,    stack: Vec::new() },
    Instruction { opcode: 0xa0, fmt: "RES 4, B",      exec: exec::res::start,    stack: Vec::new() },
    Instruction { opcode: 0xa1, fmt: "RES 4, C",      exec: exec::res::start,    stack: Vec::new() },
    Instruction { opcode: 0xa2, fmt: "RES 4, D",      exec: exec::res::start,    stack: Vec::new() },
    Instruction { opcode: 0xa3, fmt: "RES 4, E",      exec: exec::res::start,    stack: Vec::new() },
    Instruction { opcode: 0xa4, fmt: "RES 4, H",      exec: exec::res::start,    stack: Vec::new() },
    Instruction { opcode: 0xa5, fmt: "RES 4, L",      exec: exec::res::start,    stack: Vec::new() },
    Instruction { opcode: 0xa6, fmt: "RES 4, (HL)",   exec: exec::res::start,    stack: Vec::new() },
    Instruction { opcode: 0xa7, fmt: "RES 4, A",      exec: exec::res::start,    stack: Vec::new() },
    Instruction { opcode: 0xa8, fmt: "RES 5, B",      exec: exec::res::start,    stack: Vec::new() },
    Instruction { opcode: 0xa9, fmt: "RES 5, C",      exec: exec::res::start,    stack: Vec::new() },
    Instruction { opcode: 0xaa, fmt: "RES 5, D",      exec: exec::res::start,    stack: Vec::new() },
    Instruction { opcode: 0xab, fmt: "RES 5, E",      exec: exec::res::start,    stack: Vec::new() },
    Instruction { opcode: 0xac, fmt: "RES 5, H",      exec: exec::res::start,    stack: Vec::new() },
    Instruction { opcode: 0xad, fmt: "RES 5, L",      exec: exec::res::start,    stack: Vec::new() },
    Instruction { opcode: 0xae, fmt: "RES 5, (HL)",   exec: exec::res::start,    stack: Vec::new() },
    Instruction { opcode: 0xaf, fmt: "RES 5, A",      exec: exec::res::start,    stack: Vec::new() },
    Instruction { opcode: 0xb0, fmt: "RES 6, B",      exec: exec::res::start,    stack: Vec::new() },
    Instruction { opcode: 0xb1, fmt: "RES 6, C",      exec: exec::res::start,    stack: Vec::new() },
    Instruction { opcode: 0xb2, fmt: "RES 6, D",      exec: exec::res::start,    stack: Vec::new() },
    Instruction { opcode: 0xb3, fmt: "RES 6, E",      exec: exec::res::start,    stack: Vec::new() },
    Instruction { opcode: 0xb4, fmt: "RES 6, H",      exec: exec::res::start,    stack: Vec::new() },
    Instruction { opcode: 0xb5, fmt: "RES 6, L",      exec: exec::res::start,    stack: Vec::new() },
    Instruction { opcode: 0xb6, fmt: "RES 6, (HL)",   exec: exec::res::start,    stack: Vec::new() },
    Instruction { opcode: 0xb7, fmt: "RES 6, A",      exec: exec::res::start,    stack: Vec::new() },
    Instruction { opcode: 0xb8, fmt: "RES 7, B",      exec: exec::res::start,    stack: Vec::new() },
    Instruction { opcode: 0xb9, fmt: "RES 7, C",      exec: exec::res::start,    stack: Vec::new() },
    Instruction { opcode: 0xba, fmt: "RES 7, D",      exec: exec::res::start,    stack: Vec::new() },
    Instruction { opcode: 0xbb, fmt: "RES 7, E",      exec: exec::res::start,    stack: Vec::new() },
    Instruction { opcode: 0xbc, fmt: "RES 7, H",      exec: exec::res::start,    stack: Vec::new() },
    Instruction { opcode: 0xbd, fmt: "RES 7, L",      exec: exec::res::start,    stack: Vec::new() },
    Instruction { opcode: 0xbe, fmt: "RES 7, (HL)",   exec: exec::res::start,    stack: Vec::new() },
    Instruction { opcode: 0xbf, fmt: "RES 7, A",      exec: exec::res::start,    stack: Vec::new() },
    Instruction { opcode: 0xc0, fmt: "SET 0, B",      exec: exec::set::start,    stack: Vec::new() },
    Instruction { opcode: 0xc1, fmt: "SET 0, C",      exec: exec::set::start,    stack: Vec::new() },
    Instruction { opcode: 0xc2, fmt: "SET 0, D",      exec: exec::set::start,    stack: Vec::new() },
    Instruction { opcode: 0xc3, fmt: "SET 0, E",      exec: exec::set::start,    stack: Vec::new() },
    Instruction { opcode: 0xc4, fmt: "SET 0, H",      exec: exec::set::start,    stack: Vec::new() },
    Instruction { opcode: 0xc5, fmt: "SET 0, L",      exec: exec::set::start,    stack: Vec::new() },
    Instruction { opcode: 0xc6, fmt: "SET 0, (HL)",   exec: exec::set::start,    stack: Vec::new() },
    Instruction { opcode: 0xc7, fmt: "SET 0, A",      exec: exec::set::start,    stack: Vec::new() },
    Instruction { opcode: 0xc8, fmt: "SET 1, B",      exec: exec::set::start,    stack: Vec::new() },
    Instruction { opcode: 0xc9, fmt: "SET 1, C",      exec: exec::set::start,    stack: Vec::new() },
    Instruction { opcode: 0xca, fmt: "SET 1, D",      exec: exec::set::start,    stack: Vec::new() },
    Instruction { opcode: 0xcb, fmt: "SET 1, E",      exec: exec::set::start,    stack: Vec::new() },
    Instruction { opcode: 0xcc, fmt: "SET 1, H",      exec: exec::set::start,    stack: Vec::new() },
    Instruction { opcode: 0xcd, fmt: "SET 1, L",      exec: exec::set::start,    stack: Vec::new() },
    Instruction { opcode: 0xce, fmt: "SET 1, (HL)",   exec: exec::set::start,    stack: Vec::new() },
    Instruction { opcode: 0xcf, fmt: "SET 1, A",      exec: exec::set::start,    stack: Vec::new() },
    Instruction { opcode: 0xd0, fmt: "SET 2, B",      exec: exec::set::start,    stack: Vec::new() },
    Instruction { opcode: 0xd1, fmt: "SET 2, C",      exec: exec::set::start,    stack: Vec::new() },
    Instruction { opcode: 0xd2, fmt: "SET 2, D",      exec: exec::set::start,    stack: Vec::new() },
    Instruction { opcode: 0xd3, fmt: "SET 2, E",      exec: exec::set::start,    stack: Vec::new() },
    Instruction { opcode: 0xd4, fmt: "SET 2, H",      exec: exec::set::start,    stack: Vec::new() },
    Instruction { opcode: 0xd5, fmt: "SET 2, L",      exec: exec::set::start,    stack: Vec::new() },
    Instruction { opcode: 0xd6, fmt: "SET 2, (HL)",   exec: exec::set::start,    stack: Vec::new() },
    Instruction { opcode: 0xd7, fmt: "SET 2, A",      exec: exec::set::start,    stack: Vec::new() },
    Instruction { opcode: 0xd8, fmt: "SET 3, B",      exec: exec::set::start,    stack: Vec::new() },
    Instruction { opcode: 0xd9, fmt: "SET 3, C",      exec: exec::set::start,    stack: Vec::new() },
    Instruction { opcode: 0xda, fmt: "SET 3, D",      exec: exec::set::start,    stack: Vec::new() },
    Instruction { opcode: 0xdb, fmt: "SET 3, E",      exec: exec::set::start,    stack: Vec::new() },
    Instruction { opcode: 0xdc, fmt: "SET 3, H",      exec: exec::set::start,    stack: Vec::new() },
    Instruction { opcode: 0xdd, fmt: "SET 3, L",      exec: exec::set::start,    stack: Vec::new() },
    Instruction { opcode: 0xde, fmt: "SET 3, (HL)",   exec: exec::set::start,    stack: Vec::new() },
    Instruction { opcode: 0xdf, fmt: "SET 3, A",      exec: exec::set::start,    stack: Vec::new() },
    Instruction { opcode: 0xe0, fmt: "SET 4, B",      exec: exec::set::start,    stack: Vec::new() },
    Instruction { opcode: 0xe1, fmt: "SET 4, C",      exec: exec::set::start,    stack: Vec::new() },
    Instruction { opcode: 0xe2, fmt: "SET 4, D",      exec: exec::set::start,    stack: Vec::new() },
    Instruction { opcode: 0xe3, fmt: "SET 4, E",      exec: exec::set::start,    stack: Vec::new() },
    Instruction { opcode: 0xe4, fmt: "SET 4, H",      exec: exec::set::start,    stack: Vec::new() },
    Instruction { opcode: 0xe5, fmt: "SET 4, L",      exec: exec::set::start,    stack: Vec::new() },
    Instruction { opcode: 0xe6, fmt: "SET 4, (HL)",   exec: exec::set::start,    stack: Vec::new() },
    Instruction { opcode: 0xe7, fmt: "SET 4, A",      exec: exec::set::start,    stack: Vec::new() },
    Instruction { opcode: 0xe8, fmt: "SET 5, B",      exec: exec::set::start,    stack: Vec::new() },
    Instruction { opcode: 0xe9, fmt: "SET 5, C",      exec: exec::set::start,    stack: Vec::new() },
    Instruction { opcode: 0xea, fmt: "SET 5, D",      exec: exec::set::start,    stack: Vec::new() },
    Instruction { opcode: 0xeb, fmt: "SET 5, E",      exec: exec::set::start,    stack: Vec::new() },
    Instruction { opcode: 0xec, fmt: "SET 5, H",      exec: exec::set::start,    stack: Vec::new() },
    Instruction { opcode: 0xed, fmt: "SET 5, L",      exec: exec::set::start,    stack: Vec::new() },
    Instruction { opcode: 0xee, fmt: "SET 5, (HL)",   exec: exec::set::start,    stack: Vec::new() },
    Instruction { opcode: 0xef, fmt: "SET 5, A",      exec: exec::set::start,    stack: Vec::new() },
    Instruction { opcode: 0xf0, fmt: "SET 6, B",      exec: exec::set::start,    stack: Vec::new() },
    Instruction { opcode: 0xf1, fmt: "SET 6, C",      exec: exec::set::start,    stack: Vec::new() },
    Instruction { opcode: 0xf2, fmt: "SET 6, D",      exec: exec::set::start,    stack: Vec::new() },
    Instruction { opcode: 0xf3, fmt: "SET 6, E",      exec: exec::set::start,    stack: Vec::new() },
    Instruction { opcode: 0xf4, fmt: "SET 6, H",      exec: exec::set::start,    stack: Vec::new() },
    Instruction { opcode: 0xf5, fmt: "SET 6, L",      exec: exec::set::start,    stack: Vec::new() },
    Instruction { opcode: 0xf6, fmt: "SET 6, (HL)",   exec: exec::set::start,    stack: Vec::new() },
    Instruction { opcode: 0xf7, fmt: "SET 6, A",      exec: exec::set::start,    stack: Vec::new() },
    Instruction { opcode: 0xf8, fmt: "SET 7, B",      exec: exec::set::start,    stack: Vec::new() },
    Instruction { opcode: 0xf9, fmt: "SET 7, C",      exec: exec::set::start,    stack: Vec::new() },
    Instruction { opcode: 0xfa, fmt: "SET 7, D",      exec: exec::set::start,    stack: Vec::new() },
    Instruction { opcode: 0xfb, fmt: "SET 7, E",      exec: exec::set::start,    stack: Vec::new() },
    Instruction { opcode: 0xfc, fmt: "SET 7, H",      exec: exec::set::start,    stack: Vec::new() },
    Instruction { opcode: 0xfd, fmt: "SET 7, L",      exec: exec::set::start,    stack: Vec::new() },
    Instruction { opcode: 0xfe, fmt: "SET 7, (HL)",   exec: exec::set::start,    stack: Vec::new() },
    Instruction { opcode: 0xff, fmt: "SET 7, A",      exec: exec::set::start,    stack: Vec::new() },
];
