//! Instruction state machine.

use std::fmt::{Debug, Display};

use log::trace;
use thiserror::Error;

use self::exec::Operation;
use super::{Cpu, Flag, Ime, Status};
use crate::hw::pic::Interrupt;

mod exec;

type Result<T> = std::result::Result<T, Error>;

/// Instruction operation execution interface.
trait Execute {
    fn exec(self, opcode: u8, cpu: &mut Cpu) -> Result<Option<Operation>>;
}

/// CPU instruction state.
///
/// Stores the currently executing instruction together with its state. Can be
/// started and resumed.
#[derive(Clone, Debug)]
pub struct Instruction {
    code: u8,
    oper: Operation,
    fmt: &'static str,
}

impl Instruction {
    /// Constructs a new `Instruction` with the given opcode.
    #[must_use]
    pub fn new(opcode: u8) -> Self {
        DECODE[opcode as usize].clone()
    }

    /// Constructs a new prefix `Instruction` with the given opcode.
    #[must_use]
    pub fn prefix(opcode: u8) -> Self {
        PREFIX[opcode as usize].clone()
    }

    /// Constructs a new interrupt `Instruction`.
    pub(crate) fn int(int: Interrupt) -> Self {
        Self {
            code: int as u8,
            oper: Operation::Int(exec::int::Int::default()),
            fmt: int.repr(),
        }
    }

    /// Gets the instruction's opcode.
    #[must_use]
    pub fn opcode(&self) -> u8 {
        self.code
    }

    /// Executes a single stage of the instruction.
    ///
    /// # Errors
    ///
    /// Errors if the instruction failed to execute.
    pub fn exec(mut self, cpu: &mut Cpu) -> Result<Option<Self>> {
        // Execute operation
        trace!("{self:?}");
        let res = self.oper.exec(self.code, cpu)?;
        // Extract next stage
        self.oper = match res {
            Some(exec) => exec,
            None => return Ok(None),
        };
        // Return updated state
        Ok(Some(self))
    }
}

impl Display for Instruction {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", self.fmt)
    }
}

/// Helper functions.
mod helpers {
    use remus::Cell;

    use super::Cpu;

    /// Get an 8-bit register operand.
    pub fn get_op8(cpu: &mut Cpu, idx: u8) -> u8 {
        match idx {
            0x0 => cpu.file.b.load(),
            0x1 => cpu.file.c.load(),
            0x2 => cpu.file.d.load(),
            0x3 => cpu.file.e.load(),
            0x4 => cpu.file.h.load(),
            0x5 => cpu.file.l.load(),
            0x6 => cpu.readbyte(),
            0x7 => cpu.file.a.load(),
            _ => panic!("Illegal register."),
        }
    }

    /// Set an 8-bit register operand.
    pub fn set_op8(cpu: &mut Cpu, idx: u8, value: u8) {
        match idx {
            0x0 => cpu.file.b.store(value),
            0x1 => cpu.file.c.store(value),
            0x2 => cpu.file.d.store(value),
            0x3 => cpu.file.e.store(value),
            0x4 => cpu.file.h.store(value),
            0x5 => cpu.file.l.store(value),
            0x6 => cpu.writebyte(value),
            0x7 => cpu.file.a.store(value),
            _ => panic!("Illegal register."),
        };
    }
}

/// A type specifying general categories of [`Instruction`] error.
#[derive(Debug, Error)]
pub enum Error {
    #[error("illegal instruction: {0:#04X}")]
    Illegal(u8),
    #[error("unexpected opcode: {0:#04X}")]
    Opcode(u8),
    #[error("unimplemented: {0:#04X}")]
    Unimplemented(u8),
    #[error("instruction overwrite: {0:?}")]
    Overwrite(Instruction),
}

/// Instruction lookup table.
#[rustfmt::skip]
const DECODE: [Instruction; 0x100] = [
    Instruction { code: 0x00, oper: exec::nop::default(),    fmt: "NOP",            },
    Instruction { code: 0x01, oper: exec::ldw::default(),    fmt: "LD BC, n16",     },
    Instruction { code: 0x02, oper: exec::ld::default(),     fmt: "LD (BC), A",     },
    Instruction { code: 0x03, oper: exec::incw::default(),   fmt: "INC BC",         },
    Instruction { code: 0x04, oper: exec::inc::default(),    fmt: "INC B",          },
    Instruction { code: 0x05, oper: exec::dec::default(),    fmt: "DEC B",          },
    Instruction { code: 0x06, oper: exec::ld::default(),     fmt: "LD B, n8",       },
    Instruction { code: 0x07, oper: exec::rlca::default(),   fmt: "RLCA",           },
    Instruction { code: 0x08, oper: exec::ldw::default(),    fmt: "LD (a16), SP",   },
    Instruction { code: 0x09, oper: exec::addw::default(),   fmt: "ADD HL, BC",     },
    Instruction { code: 0x0a, oper: exec::ld::default(),     fmt: "LD A, (BC)",     },
    Instruction { code: 0x0b, oper: exec::decw::default(),   fmt: "DEC BC",         },
    Instruction { code: 0x0c, oper: exec::inc::default(),    fmt: "INC C",          },
    Instruction { code: 0x0d, oper: exec::dec::default(),    fmt: "DEC C",          },
    Instruction { code: 0x0e, oper: exec::ld::default(),     fmt: "LD C, n8",       },
    Instruction { code: 0x0f, oper: exec::rrca::default(),   fmt: "RRCA",           },
    Instruction { code: 0x10, oper: exec::stop::default(),   fmt: "STOP",           },
    Instruction { code: 0x11, oper: exec::ldw::default(),    fmt: "LD DE, (n16)",   },
    Instruction { code: 0x12, oper: exec::ld::default(),     fmt: "LD (DE), A",     },
    Instruction { code: 0x13, oper: exec::incw::default(),   fmt: "INC DE",         },
    Instruction { code: 0x14, oper: exec::inc::default(),    fmt: "INC D",          },
    Instruction { code: 0x15, oper: exec::dec::default(),    fmt: "DEC D",          },
    Instruction { code: 0x16, oper: exec::ld::default(),     fmt: "LD D, n8",       },
    Instruction { code: 0x17, oper: exec::rla::default(),    fmt: "RLA",            },
    Instruction { code: 0x18, oper: exec::jr::default(),     fmt: "JR e8",          },
    Instruction { code: 0x19, oper: exec::addw::default(),   fmt: "ADD HL, DE",     },
    Instruction { code: 0x1a, oper: exec::ld::default(),     fmt: "LD A, (DE)",     },
    Instruction { code: 0x1b, oper: exec::decw::default(),   fmt: "DEC DE",         },
    Instruction { code: 0x1c, oper: exec::inc::default(),    fmt: "INC E",          },
    Instruction { code: 0x1d, oper: exec::dec::default(),    fmt: "DEC E",          },
    Instruction { code: 0x1e, oper: exec::ld::default(),     fmt: "LD E, n8",       },
    Instruction { code: 0x1f, oper: exec::rra::default(),    fmt: "RRA",            },
    Instruction { code: 0x20, oper: exec::jr::default(),     fmt: "JR NZ, e8",      },
    Instruction { code: 0x21, oper: exec::ldw::default(),    fmt: "LD HL, n16",     },
    Instruction { code: 0x22, oper: exec::ld::default(),     fmt: "LD (HL+), A",    },
    Instruction { code: 0x23, oper: exec::incw::default(),   fmt: "INC HL",         },
    Instruction { code: 0x24, oper: exec::inc::default(),    fmt: "INC H",          },
    Instruction { code: 0x25, oper: exec::dec::default(),    fmt: "DEC H",          },
    Instruction { code: 0x26, oper: exec::ld::default(),     fmt: "LD H, n8",       },
    Instruction { code: 0x27, oper: exec::daa::default(),    fmt: "DAA",            },
    Instruction { code: 0x28, oper: exec::jr::default(),     fmt: "JR Z, e8",       },
    Instruction { code: 0x29, oper: exec::addw::default(),   fmt: "ADD HL, HL",     },
    Instruction { code: 0x2a, oper: exec::ld::default(),     fmt: "LD A, (HL+)",    },
    Instruction { code: 0x2b, oper: exec::decw::default(),   fmt: "DEC HL",         },
    Instruction { code: 0x2c, oper: exec::inc::default(),    fmt: "INC L",          },
    Instruction { code: 0x2d, oper: exec::dec::default(),    fmt: "DEC L",          },
    Instruction { code: 0x2e, oper: exec::ld::default(),     fmt: "LD L, n8",       },
    Instruction { code: 0x2f, oper: exec::cpl::default(),    fmt: "CPL",            },
    Instruction { code: 0x30, oper: exec::jr::default(),     fmt: "JR NC, e8",      },
    Instruction { code: 0x31, oper: exec::ldw::default(),    fmt: "LD SP, n16",     },
    Instruction { code: 0x32, oper: exec::ld::default(),     fmt: "LD (HL-), A",    },
    Instruction { code: 0x33, oper: exec::incw::default(),   fmt: "INC SP",         },
    Instruction { code: 0x34, oper: exec::inc::default(),    fmt: "INC (HL)",       },
    Instruction { code: 0x35, oper: exec::dec::default(),    fmt: "DEC (HL)",       },
    Instruction { code: 0x36, oper: exec::ld::default(),     fmt: "LD (HL), n8",    },
    Instruction { code: 0x37, oper: exec::scf::default(),    fmt: "SCF",            },
    Instruction { code: 0x38, oper: exec::jr::default(),     fmt: "JR C, e8",       },
    Instruction { code: 0x39, oper: exec::addw::default(),   fmt: "ADD HL, SP",     },
    Instruction { code: 0x3a, oper: exec::ld::default(),     fmt: "LD A, (HL-)",    },
    Instruction { code: 0x3b, oper: exec::decw::default(),   fmt: "DEC SP",         },
    Instruction { code: 0x3c, oper: exec::inc::default(),    fmt: "INC A",          },
    Instruction { code: 0x3d, oper: exec::dec::default(),    fmt: "DEC A",          },
    Instruction { code: 0x3e, oper: exec::ld::default(),     fmt: "LD A, n8",       },
    Instruction { code: 0x3f, oper: exec::ccf::default(),    fmt: "CCP",            },
    Instruction { code: 0x40, oper: exec::ld::default(),     fmt: "LD B, B",        },
    Instruction { code: 0x41, oper: exec::ld::default(),     fmt: "LD B, C",        },
    Instruction { code: 0x42, oper: exec::ld::default(),     fmt: "LD B, D",        },
    Instruction { code: 0x43, oper: exec::ld::default(),     fmt: "LD B, E",        },
    Instruction { code: 0x44, oper: exec::ld::default(),     fmt: "LD B, H",        },
    Instruction { code: 0x45, oper: exec::ld::default(),     fmt: "LD B, L",        },
    Instruction { code: 0x46, oper: exec::ld::default(),     fmt: "LD B, (HL)",     },
    Instruction { code: 0x47, oper: exec::ld::default(),     fmt: "LD B, A",        },
    Instruction { code: 0x48, oper: exec::ld::default(),     fmt: "LD C, B",        },
    Instruction { code: 0x49, oper: exec::ld::default(),     fmt: "LD C, C",        },
    Instruction { code: 0x4a, oper: exec::ld::default(),     fmt: "LD C, D",        },
    Instruction { code: 0x4b, oper: exec::ld::default(),     fmt: "LD C, E",        },
    Instruction { code: 0x4c, oper: exec::ld::default(),     fmt: "LD C, H",        },
    Instruction { code: 0x4d, oper: exec::ld::default(),     fmt: "LD C, L",        },
    Instruction { code: 0x4e, oper: exec::ld::default(),     fmt: "LD C, (HL)",     },
    Instruction { code: 0x4f, oper: exec::ld::default(),     fmt: "LD C, A",        },
    Instruction { code: 0x50, oper: exec::ld::default(),     fmt: "LD D, B",        },
    Instruction { code: 0x51, oper: exec::ld::default(),     fmt: "LD D, C",        },
    Instruction { code: 0x52, oper: exec::ld::default(),     fmt: "LD D, D",        },
    Instruction { code: 0x53, oper: exec::ld::default(),     fmt: "LD D, E",        },
    Instruction { code: 0x54, oper: exec::ld::default(),     fmt: "LD D, H",        },
    Instruction { code: 0x55, oper: exec::ld::default(),     fmt: "LD D, L",        },
    Instruction { code: 0x56, oper: exec::ld::default(),     fmt: "LD D, (HL)",     },
    Instruction { code: 0x57, oper: exec::ld::default(),     fmt: "LD D, A",        },
    Instruction { code: 0x58, oper: exec::ld::default(),     fmt: "LD E, B",        },
    Instruction { code: 0x59, oper: exec::ld::default(),     fmt: "LD E, C",        },
    Instruction { code: 0x5a, oper: exec::ld::default(),     fmt: "LD E, D",        },
    Instruction { code: 0x5b, oper: exec::ld::default(),     fmt: "LD E, E",        },
    Instruction { code: 0x5c, oper: exec::ld::default(),     fmt: "LD E, H",        },
    Instruction { code: 0x5d, oper: exec::ld::default(),     fmt: "LD E, L",        },
    Instruction { code: 0x5e, oper: exec::ld::default(),     fmt: "LD E, (HL)",     },
    Instruction { code: 0x5f, oper: exec::ld::default(),     fmt: "LD E, A",        },
    Instruction { code: 0x60, oper: exec::ld::default(),     fmt: "LD H, B",        },
    Instruction { code: 0x61, oper: exec::ld::default(),     fmt: "LD H, C",        },
    Instruction { code: 0x62, oper: exec::ld::default(),     fmt: "LD H, D",        },
    Instruction { code: 0x63, oper: exec::ld::default(),     fmt: "LD H, E",        },
    Instruction { code: 0x64, oper: exec::ld::default(),     fmt: "LD H, H",        },
    Instruction { code: 0x65, oper: exec::ld::default(),     fmt: "LD H, L",        },
    Instruction { code: 0x66, oper: exec::ld::default(),     fmt: "LD H, (HL)",     },
    Instruction { code: 0x67, oper: exec::ld::default(),     fmt: "LD H, A",        },
    Instruction { code: 0x68, oper: exec::ld::default(),     fmt: "LD L, B",        },
    Instruction { code: 0x69, oper: exec::ld::default(),     fmt: "LD L, C",        },
    Instruction { code: 0x6a, oper: exec::ld::default(),     fmt: "LD L, D",        },
    Instruction { code: 0x6b, oper: exec::ld::default(),     fmt: "LD L, E",        },
    Instruction { code: 0x6c, oper: exec::ld::default(),     fmt: "LD L, H",        },
    Instruction { code: 0x6d, oper: exec::ld::default(),     fmt: "LD L, L",        },
    Instruction { code: 0x6e, oper: exec::ld::default(),     fmt: "LD L, (HL)",     },
    Instruction { code: 0x6f, oper: exec::ld::default(),     fmt: "LD L, A",        },
    Instruction { code: 0x70, oper: exec::ld::default(),     fmt: "LD (HL), B",     },
    Instruction { code: 0x71, oper: exec::ld::default(),     fmt: "LD (HL), C",     },
    Instruction { code: 0x72, oper: exec::ld::default(),     fmt: "LD (HL), D",     },
    Instruction { code: 0x73, oper: exec::ld::default(),     fmt: "LD (HL), E",     },
    Instruction { code: 0x74, oper: exec::ld::default(),     fmt: "LD (HL), H",     },
    Instruction { code: 0x75, oper: exec::ld::default(),     fmt: "LD (HL), L",     },
    Instruction { code: 0x76, oper: exec::halt::default(),   fmt: "HALT",           },
    Instruction { code: 0x77, oper: exec::ld::default(),     fmt: "LD (HL), A",     },
    Instruction { code: 0x78, oper: exec::ld::default(),     fmt: "LD A, B",        },
    Instruction { code: 0x79, oper: exec::ld::default(),     fmt: "LD A, C",        },
    Instruction { code: 0x7a, oper: exec::ld::default(),     fmt: "LD A, D",        },
    Instruction { code: 0x7b, oper: exec::ld::default(),     fmt: "LD A, E",        },
    Instruction { code: 0x7c, oper: exec::ld::default(),     fmt: "LD A, H",        },
    Instruction { code: 0x7d, oper: exec::ld::default(),     fmt: "LD A, L",        },
    Instruction { code: 0x7e, oper: exec::ld::default(),     fmt: "LD A, (HL)",     },
    Instruction { code: 0x7f, oper: exec::ld::default(),     fmt: "LD A, A",        },
    Instruction { code: 0x80, oper: exec::add::default(),    fmt: "ADD A, B",       },
    Instruction { code: 0x81, oper: exec::add::default(),    fmt: "ADD A, C",       },
    Instruction { code: 0x82, oper: exec::add::default(),    fmt: "ADD A, D",       },
    Instruction { code: 0x83, oper: exec::add::default(),    fmt: "ADD A, E",       },
    Instruction { code: 0x84, oper: exec::add::default(),    fmt: "ADD A, H",       },
    Instruction { code: 0x85, oper: exec::add::default(),    fmt: "ADD A, L",       },
    Instruction { code: 0x86, oper: exec::add::default(),    fmt: "ADD A, (HL)",    },
    Instruction { code: 0x87, oper: exec::add::default(),    fmt: "ADD A, A",       },
    Instruction { code: 0x88, oper: exec::adc::default(),    fmt: "ADC A, B",       },
    Instruction { code: 0x89, oper: exec::adc::default(),    fmt: "ADC A, C",       },
    Instruction { code: 0x8a, oper: exec::adc::default(),    fmt: "ADC A, D",       },
    Instruction { code: 0x8b, oper: exec::adc::default(),    fmt: "ADC A, E",       },
    Instruction { code: 0x8c, oper: exec::adc::default(),    fmt: "ADC A, H",       },
    Instruction { code: 0x8d, oper: exec::adc::default(),    fmt: "ADC A, L",       },
    Instruction { code: 0x8e, oper: exec::adc::default(),    fmt: "ADC A, (HL)",    },
    Instruction { code: 0x8f, oper: exec::adc::default(),    fmt: "ADC A, A",       },
    Instruction { code: 0x90, oper: exec::sub::default(),    fmt: "SUB A, B",       },
    Instruction { code: 0x91, oper: exec::sub::default(),    fmt: "SUB A, C",       },
    Instruction { code: 0x92, oper: exec::sub::default(),    fmt: "SUB A, D",       },
    Instruction { code: 0x93, oper: exec::sub::default(),    fmt: "SUB A, E",       },
    Instruction { code: 0x94, oper: exec::sub::default(),    fmt: "SUB A, H",       },
    Instruction { code: 0x95, oper: exec::sub::default(),    fmt: "SUB A, L",       },
    Instruction { code: 0x96, oper: exec::sub::default(),    fmt: "SUB A, (HL)",    },
    Instruction { code: 0x97, oper: exec::sub::default(),    fmt: "SUB A, A",       },
    Instruction { code: 0x98, oper: exec::sbc::default(),    fmt: "SBC A, B",       },
    Instruction { code: 0x99, oper: exec::sbc::default(),    fmt: "SBC A, C",       },
    Instruction { code: 0x9a, oper: exec::sbc::default(),    fmt: "SBC A, D",       },
    Instruction { code: 0x9b, oper: exec::sbc::default(),    fmt: "SBC A, E",       },
    Instruction { code: 0x9c, oper: exec::sbc::default(),    fmt: "SBC A, H",       },
    Instruction { code: 0x9d, oper: exec::sbc::default(),    fmt: "SBC A, L",       },
    Instruction { code: 0x9e, oper: exec::sbc::default(),    fmt: "SBC A, (HL)",    },
    Instruction { code: 0x9f, oper: exec::sbc::default(),    fmt: "SBC A, A",       },
    Instruction { code: 0xa0, oper: exec::and::default(),    fmt: "AND A, B",       },
    Instruction { code: 0xa1, oper: exec::and::default(),    fmt: "AND A, C",       },
    Instruction { code: 0xa2, oper: exec::and::default(),    fmt: "AND A, D",       },
    Instruction { code: 0xa3, oper: exec::and::default(),    fmt: "AND A, E",       },
    Instruction { code: 0xa4, oper: exec::and::default(),    fmt: "AND A, H",       },
    Instruction { code: 0xa5, oper: exec::and::default(),    fmt: "AND A, L",       },
    Instruction { code: 0xa6, oper: exec::and::default(),    fmt: "AND A, (HL)",    },
    Instruction { code: 0xa7, oper: exec::and::default(),    fmt: "AND A, A",       },
    Instruction { code: 0xa8, oper: exec::xor::default(),    fmt: "XOR A, B",       },
    Instruction { code: 0xa9, oper: exec::xor::default(),    fmt: "XOR A, C",       },
    Instruction { code: 0xaa, oper: exec::xor::default(),    fmt: "XOR A, D",       },
    Instruction { code: 0xab, oper: exec::xor::default(),    fmt: "XOR A, E",       },
    Instruction { code: 0xac, oper: exec::xor::default(),    fmt: "XOR A, H",       },
    Instruction { code: 0xad, oper: exec::xor::default(),    fmt: "XOR A, L",       },
    Instruction { code: 0xae, oper: exec::xor::default(),    fmt: "XOR A, (HL)",    },
    Instruction { code: 0xaf, oper: exec::xor::default(),    fmt: "XOR A, A",       },
    Instruction { code: 0xb0, oper: exec::or::default(),     fmt: "OR A, B",        },
    Instruction { code: 0xb1, oper: exec::or::default(),     fmt: "OR A, C",        },
    Instruction { code: 0xb2, oper: exec::or::default(),     fmt: "OR A, D",        },
    Instruction { code: 0xb3, oper: exec::or::default(),     fmt: "OR A, E",        },
    Instruction { code: 0xb4, oper: exec::or::default(),     fmt: "OR A, H",        },
    Instruction { code: 0xb5, oper: exec::or::default(),     fmt: "OR A, L",        },
    Instruction { code: 0xb6, oper: exec::or::default(),     fmt: "OR A, (HL)",     },
    Instruction { code: 0xb7, oper: exec::or::default(),     fmt: "OR A, A",        },
    Instruction { code: 0xb8, oper: exec::cp::default(),     fmt: "CP A, B",        },
    Instruction { code: 0xb9, oper: exec::cp::default(),     fmt: "CP A, C",        },
    Instruction { code: 0xba, oper: exec::cp::default(),     fmt: "CP A, D",        },
    Instruction { code: 0xbb, oper: exec::cp::default(),     fmt: "CP A, E",        },
    Instruction { code: 0xbc, oper: exec::cp::default(),     fmt: "CP A, H",        },
    Instruction { code: 0xbd, oper: exec::cp::default(),     fmt: "CP A, L",        },
    Instruction { code: 0xbe, oper: exec::cp::default(),     fmt: "CP A, (HL)",     },
    Instruction { code: 0xbf, oper: exec::cp::default(),     fmt: "CP A, A",        },
    Instruction { code: 0xc0, oper: exec::ret::default(),    fmt: "RET NZ",         },
    Instruction { code: 0xc1, oper: exec::pop::default(),    fmt: "POP BC",         },
    Instruction { code: 0xc2, oper: exec::jp::default(),     fmt: "JP NZ, a16",     },
    Instruction { code: 0xc3, oper: exec::jp::default(),     fmt: "JP a16",         },
    Instruction { code: 0xc4, oper: exec::call::default(),   fmt: "CALL NZ, a16",   },
    Instruction { code: 0xc5, oper: exec::push::default(),   fmt: "PUSH BC",        },
    Instruction { code: 0xc6, oper: exec::add::default(),    fmt: "ADD A, n8",      },
    Instruction { code: 0xc7, oper: exec::rst::default(),    fmt: "RST 00H",        },
    Instruction { code: 0xc8, oper: exec::ret::default(),    fmt: "RET Z",          },
    Instruction { code: 0xc9, oper: exec::ret::default(),    fmt: "RET",            },
    Instruction { code: 0xca, oper: exec::jp::default(),     fmt: "JP Z, a16",      },
    Instruction { code: 0xcb, oper: exec::prefix::default(), fmt: "PREFIX",         },
    Instruction { code: 0xcc, oper: exec::call::default(),   fmt: "CALL Z, a16",    },
    Instruction { code: 0xcd, oper: exec::call::default(),   fmt: "CALL a16",       },
    Instruction { code: 0xce, oper: exec::adc::default(),    fmt: "ADC A, n8",      },
    Instruction { code: 0xcf, oper: exec::rst::default(),    fmt: "RST 08H",        },
    Instruction { code: 0xd0, oper: exec::ret::default(),    fmt: "RET NC",         },
    Instruction { code: 0xd1, oper: exec::pop::default(),    fmt: "POP DE",         },
    Instruction { code: 0xd2, oper: exec::jp::default(),     fmt: "JP NC, a16",     },
    Instruction { code: 0xd3, oper: exec::unused::default(), fmt: "UNUSED",         },
    Instruction { code: 0xd4, oper: exec::call::default(),   fmt: "CALL NC, a16",   },
    Instruction { code: 0xd5, oper: exec::push::default(),   fmt: "PUSH DE",        },
    Instruction { code: 0xd6, oper: exec::sub::default(),    fmt: "SUB n8",         },
    Instruction { code: 0xd7, oper: exec::rst::default(),    fmt: "RST 10H",        },
    Instruction { code: 0xd8, oper: exec::ret::default(),    fmt: "RET C",          },
    Instruction { code: 0xd9, oper: exec::reti::default(),   fmt: "RETI",           },
    Instruction { code: 0xda, oper: exec::jp::default(),     fmt: "JP C, a16",      },
    Instruction { code: 0xdb, oper: exec::unused::default(), fmt: "UNUSED",         },
    Instruction { code: 0xdc, oper: exec::call::default(),   fmt: "CALL C, a16",    },
    Instruction { code: 0xdd, oper: exec::unused::default(), fmt: "UNUSED",         },
    Instruction { code: 0xde, oper: exec::sbc::default(),    fmt: "SBC A, n8",      },
    Instruction { code: 0xdf, oper: exec::rst::default(),    fmt: "RST 18H",        },
    Instruction { code: 0xe0, oper: exec::ldh::default(),    fmt: "LDH (a8), A",    },
    Instruction { code: 0xe1, oper: exec::pop::default(),    fmt: "POP HL",         },
    Instruction { code: 0xe2, oper: exec::ldh::default(),    fmt: "LD (C), A",      },
    Instruction { code: 0xe3, oper: exec::unused::default(), fmt: "UNUSED",         },
    Instruction { code: 0xe4, oper: exec::unused::default(), fmt: "UNUSED",         },
    Instruction { code: 0xe5, oper: exec::push::default(),   fmt: "PUSH HL",        },
    Instruction { code: 0xe6, oper: exec::and::default(),    fmt: "AND A, n8",      },
    Instruction { code: 0xe7, oper: exec::rst::default(),    fmt: "RST 20H",        },
    Instruction { code: 0xe8, oper: exec::addw::default(),   fmt: "ADD SP, e8",     },
    Instruction { code: 0xe9, oper: exec::jp::default(),     fmt: "JP HL",          },
    Instruction { code: 0xea, oper: exec::ld::default(),     fmt: "LD (a16), A",    },
    Instruction { code: 0xeb, oper: exec::unused::default(), fmt: "UNUSED",         },
    Instruction { code: 0xec, oper: exec::unused::default(), fmt: "UNUSED",         },
    Instruction { code: 0xed, oper: exec::unused::default(), fmt: "UNUSED",         },
    Instruction { code: 0xee, oper: exec::xor::default(),    fmt: "XOR A, n8",      },
    Instruction { code: 0xef, oper: exec::rst::default(),    fmt: "RST 28H",        },
    Instruction { code: 0xf0, oper: exec::ldh::default(),    fmt: "LDH A, (a8)",    },
    Instruction { code: 0xf1, oper: exec::pop::default(),    fmt: "POP AF",         },
    Instruction { code: 0xf2, oper: exec::ldh::default(),    fmt: "LD A, (C)",      },
    Instruction { code: 0xf3, oper: exec::di::default(),     fmt: "DI",             },
    Instruction { code: 0xf4, oper: exec::unused::default(), fmt: "UNUSED",         },
    Instruction { code: 0xf5, oper: exec::push::default(),   fmt: "PUSH AF",        },
    Instruction { code: 0xf6, oper: exec::or::default(),     fmt: "OR A, n8",       },
    Instruction { code: 0xf7, oper: exec::rst::default(),    fmt: "RST 30H",        },
    Instruction { code: 0xf8, oper: exec::ldw::default(),    fmt: "LD HL, SP + e8", },
    Instruction { code: 0xf9, oper: exec::ldw::default(),    fmt: "LD SP, HL",      },
    Instruction { code: 0xfa, oper: exec::ld::default(),     fmt: "LD A, (a16)",    },
    Instruction { code: 0xfb, oper: exec::ei::default(),     fmt: "EI",             },
    Instruction { code: 0xfc, oper: exec::unused::default(), fmt: "UNUSED",         },
    Instruction { code: 0xfd, oper: exec::unused::default(), fmt: "UNUSED",         },
    Instruction { code: 0xfe, oper: exec::cp::default(),     fmt: "CP A, n8",       },
    Instruction { code: 0xff, oper: exec::rst::default(),    fmt: "RST 38H",        },
];

/// Prefix lookup table.
#[rustfmt::skip]
const PREFIX: [Instruction; 0x100] = [
    Instruction { code: 0x00, oper: exec::rlc::default(),  fmt: "RLC B",       },
    Instruction { code: 0x01, oper: exec::rlc::default(),  fmt: "RLC C",       },
    Instruction { code: 0x02, oper: exec::rlc::default(),  fmt: "RLC D",       },
    Instruction { code: 0x03, oper: exec::rlc::default(),  fmt: "RLC E",       },
    Instruction { code: 0x04, oper: exec::rlc::default(),  fmt: "RLC H",       },
    Instruction { code: 0x05, oper: exec::rlc::default(),  fmt: "RLC L",       },
    Instruction { code: 0x06, oper: exec::rlc::default(),  fmt: "RLC (HL)",    },
    Instruction { code: 0x07, oper: exec::rlc::default(),  fmt: "RLC A",       },
    Instruction { code: 0x08, oper: exec::rrc::default(),  fmt: "RRC B",       },
    Instruction { code: 0x09, oper: exec::rrc::default(),  fmt: "RRC C",       },
    Instruction { code: 0x0a, oper: exec::rrc::default(),  fmt: "RRC D",       },
    Instruction { code: 0x0b, oper: exec::rrc::default(),  fmt: "RRC E",       },
    Instruction { code: 0x0c, oper: exec::rrc::default(),  fmt: "RRC H",       },
    Instruction { code: 0x0d, oper: exec::rrc::default(),  fmt: "RRC L",       },
    Instruction { code: 0x0e, oper: exec::rrc::default(),  fmt: "RRC (HL)",    },
    Instruction { code: 0x0f, oper: exec::rrc::default(),  fmt: "RRC A",       },
    Instruction { code: 0x10, oper: exec::rl::default(),   fmt: "RL B",        },
    Instruction { code: 0x11, oper: exec::rl::default(),   fmt: "RL C",        },
    Instruction { code: 0x12, oper: exec::rl::default(),   fmt: "RL D",        },
    Instruction { code: 0x13, oper: exec::rl::default(),   fmt: "RL E",        },
    Instruction { code: 0x14, oper: exec::rl::default(),   fmt: "RL H",        },
    Instruction { code: 0x15, oper: exec::rl::default(),   fmt: "RL L",        },
    Instruction { code: 0x16, oper: exec::rl::default(),   fmt: "RL (HL)",     },
    Instruction { code: 0x17, oper: exec::rl::default(),   fmt: "RL A",        },
    Instruction { code: 0x18, oper: exec::rr::default(),   fmt: "RR B",        },
    Instruction { code: 0x19, oper: exec::rr::default(),   fmt: "RR C",        },
    Instruction { code: 0x1a, oper: exec::rr::default(),   fmt: "RR D",        },
    Instruction { code: 0x1b, oper: exec::rr::default(),   fmt: "RR E",        },
    Instruction { code: 0x1c, oper: exec::rr::default(),   fmt: "RR H",        },
    Instruction { code: 0x1d, oper: exec::rr::default(),   fmt: "RR L",        },
    Instruction { code: 0x1e, oper: exec::rr::default(),   fmt: "RR (HL)",     },
    Instruction { code: 0x1f, oper: exec::rr::default(),   fmt: "RR A",        },
    Instruction { code: 0x20, oper: exec::sla::default(),  fmt: "SLA B",       },
    Instruction { code: 0x21, oper: exec::sla::default(),  fmt: "SLA C",       },
    Instruction { code: 0x22, oper: exec::sla::default(),  fmt: "SLA D",       },
    Instruction { code: 0x23, oper: exec::sla::default(),  fmt: "SLA E",       },
    Instruction { code: 0x24, oper: exec::sla::default(),  fmt: "SLA H",       },
    Instruction { code: 0x25, oper: exec::sla::default(),  fmt: "SLA L",       },
    Instruction { code: 0x26, oper: exec::sla::default(),  fmt: "SLA (HL)",    },
    Instruction { code: 0x27, oper: exec::sla::default(),  fmt: "SLA A",       },
    Instruction { code: 0x28, oper: exec::sra::default(),  fmt: "SRA B",       },
    Instruction { code: 0x29, oper: exec::sra::default(),  fmt: "SRA C",       },
    Instruction { code: 0x2a, oper: exec::sra::default(),  fmt: "SRA D",       },
    Instruction { code: 0x2b, oper: exec::sra::default(),  fmt: "SRA E",       },
    Instruction { code: 0x2c, oper: exec::sra::default(),  fmt: "SRA H",       },
    Instruction { code: 0x2d, oper: exec::sra::default(),  fmt: "SRA L",       },
    Instruction { code: 0x2e, oper: exec::sra::default(),  fmt: "SRA (HL)",    },
    Instruction { code: 0x2f, oper: exec::sra::default(),  fmt: "SRA A",       },
    Instruction { code: 0x30, oper: exec::swap::default(), fmt: "SWAP B",      },
    Instruction { code: 0x31, oper: exec::swap::default(), fmt: "SWAP C",      },
    Instruction { code: 0x32, oper: exec::swap::default(), fmt: "SWAP D",      },
    Instruction { code: 0x33, oper: exec::swap::default(), fmt: "SWAP E",      },
    Instruction { code: 0x34, oper: exec::swap::default(), fmt: "SWAP H",      },
    Instruction { code: 0x35, oper: exec::swap::default(), fmt: "SWAP L",      },
    Instruction { code: 0x36, oper: exec::swap::default(), fmt: "SWAP (HL)",   },
    Instruction { code: 0x37, oper: exec::swap::default(), fmt: "SWAP A",      },
    Instruction { code: 0x38, oper: exec::srl::default(),  fmt: "SRL B",       },
    Instruction { code: 0x39, oper: exec::srl::default(),  fmt: "SRL C",       },
    Instruction { code: 0x3a, oper: exec::srl::default(),  fmt: "SRL D",       },
    Instruction { code: 0x3b, oper: exec::srl::default(),  fmt: "SRL E",       },
    Instruction { code: 0x3c, oper: exec::srl::default(),  fmt: "SRL H",       },
    Instruction { code: 0x3d, oper: exec::srl::default(),  fmt: "SRL L",       },
    Instruction { code: 0x3e, oper: exec::srl::default(),  fmt: "SRL (HL)",    },
    Instruction { code: 0x3f, oper: exec::srl::default(),  fmt: "SRL A",       },
    Instruction { code: 0x40, oper: exec::bit::default(),  fmt: "BIT 0, B",    },
    Instruction { code: 0x41, oper: exec::bit::default(),  fmt: "BIT 0, C",    },
    Instruction { code: 0x42, oper: exec::bit::default(),  fmt: "BIT 0, D",    },
    Instruction { code: 0x43, oper: exec::bit::default(),  fmt: "BIT 0, E",    },
    Instruction { code: 0x44, oper: exec::bit::default(),  fmt: "BIT 0, H",    },
    Instruction { code: 0x45, oper: exec::bit::default(),  fmt: "BIT 0, L",    },
    Instruction { code: 0x46, oper: exec::bit::default(),  fmt: "BIT 0, (HL)", },
    Instruction { code: 0x47, oper: exec::bit::default(),  fmt: "BIT 0, A",    },
    Instruction { code: 0x48, oper: exec::bit::default(),  fmt: "BIT 1, B",    },
    Instruction { code: 0x49, oper: exec::bit::default(),  fmt: "BIT 1, C",    },
    Instruction { code: 0x4a, oper: exec::bit::default(),  fmt: "BIT 1, D",    },
    Instruction { code: 0x4b, oper: exec::bit::default(),  fmt: "BIT 1, E",    },
    Instruction { code: 0x4c, oper: exec::bit::default(),  fmt: "BIT 1, H",    },
    Instruction { code: 0x4d, oper: exec::bit::default(),  fmt: "BIT 1, L",    },
    Instruction { code: 0x4e, oper: exec::bit::default(),  fmt: "BIT 1, (HL)", },
    Instruction { code: 0x4f, oper: exec::bit::default(),  fmt: "BIT 1, A",    },
    Instruction { code: 0x50, oper: exec::bit::default(),  fmt: "BIT 2, B",    },
    Instruction { code: 0x51, oper: exec::bit::default(),  fmt: "BIT 2, C",    },
    Instruction { code: 0x52, oper: exec::bit::default(),  fmt: "BIT 2, D",    },
    Instruction { code: 0x53, oper: exec::bit::default(),  fmt: "BIT 2, E",    },
    Instruction { code: 0x54, oper: exec::bit::default(),  fmt: "BIT 2, H",    },
    Instruction { code: 0x55, oper: exec::bit::default(),  fmt: "BIT 2, L",    },
    Instruction { code: 0x56, oper: exec::bit::default(),  fmt: "BIT 2, (HL)", },
    Instruction { code: 0x57, oper: exec::bit::default(),  fmt: "BIT 2, A",    },
    Instruction { code: 0x58, oper: exec::bit::default(),  fmt: "BIT 3, B",    },
    Instruction { code: 0x59, oper: exec::bit::default(),  fmt: "BIT 3, C",    },
    Instruction { code: 0x5a, oper: exec::bit::default(),  fmt: "BIT 3, D",    },
    Instruction { code: 0x5b, oper: exec::bit::default(),  fmt: "BIT 3, E",    },
    Instruction { code: 0x5c, oper: exec::bit::default(),  fmt: "BIT 3, H",    },
    Instruction { code: 0x5d, oper: exec::bit::default(),  fmt: "BIT 3, L",    },
    Instruction { code: 0x5e, oper: exec::bit::default(),  fmt: "BIT 3, (HL)", },
    Instruction { code: 0x5f, oper: exec::bit::default(),  fmt: "BIT 3, A",    },
    Instruction { code: 0x60, oper: exec::bit::default(),  fmt: "BIT 4, B",    },
    Instruction { code: 0x61, oper: exec::bit::default(),  fmt: "BIT 4, C",    },
    Instruction { code: 0x62, oper: exec::bit::default(),  fmt: "BIT 4, D",    },
    Instruction { code: 0x63, oper: exec::bit::default(),  fmt: "BIT 4, E",    },
    Instruction { code: 0x64, oper: exec::bit::default(),  fmt: "BIT 4, H",    },
    Instruction { code: 0x65, oper: exec::bit::default(),  fmt: "BIT 4, L",    },
    Instruction { code: 0x66, oper: exec::bit::default(),  fmt: "BIT 4, (HL)", },
    Instruction { code: 0x67, oper: exec::bit::default(),  fmt: "BIT 4, A",    },
    Instruction { code: 0x68, oper: exec::bit::default(),  fmt: "BIT 5, B",    },
    Instruction { code: 0x69, oper: exec::bit::default(),  fmt: "BIT 5, C",    },
    Instruction { code: 0x6a, oper: exec::bit::default(),  fmt: "BIT 5, D",    },
    Instruction { code: 0x6b, oper: exec::bit::default(),  fmt: "BIT 5, E",    },
    Instruction { code: 0x6c, oper: exec::bit::default(),  fmt: "BIT 5, H",    },
    Instruction { code: 0x6d, oper: exec::bit::default(),  fmt: "BIT 5, L",    },
    Instruction { code: 0x6e, oper: exec::bit::default(),  fmt: "BIT 5, (HL)", },
    Instruction { code: 0x6f, oper: exec::bit::default(),  fmt: "BIT 5, A",    },
    Instruction { code: 0x70, oper: exec::bit::default(),  fmt: "BIT 6, B",    },
    Instruction { code: 0x71, oper: exec::bit::default(),  fmt: "BIT 6, C",    },
    Instruction { code: 0x72, oper: exec::bit::default(),  fmt: "BIT 6, D",    },
    Instruction { code: 0x73, oper: exec::bit::default(),  fmt: "BIT 6, E",    },
    Instruction { code: 0x74, oper: exec::bit::default(),  fmt: "BIT 6, H",    },
    Instruction { code: 0x75, oper: exec::bit::default(),  fmt: "BIT 6, L",    },
    Instruction { code: 0x76, oper: exec::bit::default(),  fmt: "BIT 6, (HL)", },
    Instruction { code: 0x77, oper: exec::bit::default(),  fmt: "BIT 6, A",    },
    Instruction { code: 0x78, oper: exec::bit::default(),  fmt: "BIT 7, B",    },
    Instruction { code: 0x79, oper: exec::bit::default(),  fmt: "BIT 7, C",    },
    Instruction { code: 0x7a, oper: exec::bit::default(),  fmt: "BIT 7, D",    },
    Instruction { code: 0x7b, oper: exec::bit::default(),  fmt: "BIT 7, E",    },
    Instruction { code: 0x7c, oper: exec::bit::default(),  fmt: "BIT 7, H",    },
    Instruction { code: 0x7d, oper: exec::bit::default(),  fmt: "BIT 7, L",    },
    Instruction { code: 0x7e, oper: exec::bit::default(),  fmt: "BIT 7, (HL)", },
    Instruction { code: 0x7f, oper: exec::bit::default(),  fmt: "BIT 7, A",    },
    Instruction { code: 0x80, oper: exec::res::default(),  fmt: "RES 0, B",    },
    Instruction { code: 0x81, oper: exec::res::default(),  fmt: "RES 0, C",    },
    Instruction { code: 0x82, oper: exec::res::default(),  fmt: "RES 0, D",    },
    Instruction { code: 0x83, oper: exec::res::default(),  fmt: "RES 0, E",    },
    Instruction { code: 0x84, oper: exec::res::default(),  fmt: "RES 0, H",    },
    Instruction { code: 0x85, oper: exec::res::default(),  fmt: "RES 0, L",    },
    Instruction { code: 0x86, oper: exec::res::default(),  fmt: "RES 0, (HL)", },
    Instruction { code: 0x87, oper: exec::res::default(),  fmt: "RES 0, A",    },
    Instruction { code: 0x88, oper: exec::res::default(),  fmt: "RES 1, B",    },
    Instruction { code: 0x89, oper: exec::res::default(),  fmt: "RES 1, C",    },
    Instruction { code: 0x8a, oper: exec::res::default(),  fmt: "RES 1, D",    },
    Instruction { code: 0x8b, oper: exec::res::default(),  fmt: "RES 1, E",    },
    Instruction { code: 0x8c, oper: exec::res::default(),  fmt: "RES 1, H",    },
    Instruction { code: 0x8d, oper: exec::res::default(),  fmt: "RES 1, L",    },
    Instruction { code: 0x8e, oper: exec::res::default(),  fmt: "RES 1, (HL)", },
    Instruction { code: 0x8f, oper: exec::res::default(),  fmt: "RES 1, A",    },
    Instruction { code: 0x90, oper: exec::res::default(),  fmt: "RES 2, B",    },
    Instruction { code: 0x91, oper: exec::res::default(),  fmt: "RES 2, C",    },
    Instruction { code: 0x92, oper: exec::res::default(),  fmt: "RES 2, D",    },
    Instruction { code: 0x93, oper: exec::res::default(),  fmt: "RES 2, E",    },
    Instruction { code: 0x94, oper: exec::res::default(),  fmt: "RES 2, H",    },
    Instruction { code: 0x95, oper: exec::res::default(),  fmt: "RES 2, L",    },
    Instruction { code: 0x96, oper: exec::res::default(),  fmt: "RES 2, (HL)", },
    Instruction { code: 0x97, oper: exec::res::default(),  fmt: "RES 2, A",    },
    Instruction { code: 0x98, oper: exec::res::default(),  fmt: "RES 3, B",    },
    Instruction { code: 0x99, oper: exec::res::default(),  fmt: "RES 3, C",    },
    Instruction { code: 0x9a, oper: exec::res::default(),  fmt: "RES 3, D",    },
    Instruction { code: 0x9b, oper: exec::res::default(),  fmt: "RES 3, E",    },
    Instruction { code: 0x9c, oper: exec::res::default(),  fmt: "RES 3, H",    },
    Instruction { code: 0x9d, oper: exec::res::default(),  fmt: "RES 3, L",    },
    Instruction { code: 0x9e, oper: exec::res::default(),  fmt: "RES 3, (HL)", },
    Instruction { code: 0x9f, oper: exec::res::default(),  fmt: "RES 3, A",    },
    Instruction { code: 0xa0, oper: exec::res::default(),  fmt: "RES 4, B",    },
    Instruction { code: 0xa1, oper: exec::res::default(),  fmt: "RES 4, C",    },
    Instruction { code: 0xa2, oper: exec::res::default(),  fmt: "RES 4, D",    },
    Instruction { code: 0xa3, oper: exec::res::default(),  fmt: "RES 4, E",    },
    Instruction { code: 0xa4, oper: exec::res::default(),  fmt: "RES 4, H",    },
    Instruction { code: 0xa5, oper: exec::res::default(),  fmt: "RES 4, L",    },
    Instruction { code: 0xa6, oper: exec::res::default(),  fmt: "RES 4, (HL)", },
    Instruction { code: 0xa7, oper: exec::res::default(),  fmt: "RES 4, A",    },
    Instruction { code: 0xa8, oper: exec::res::default(),  fmt: "RES 5, B",    },
    Instruction { code: 0xa9, oper: exec::res::default(),  fmt: "RES 5, C",    },
    Instruction { code: 0xaa, oper: exec::res::default(),  fmt: "RES 5, D",    },
    Instruction { code: 0xab, oper: exec::res::default(),  fmt: "RES 5, E",    },
    Instruction { code: 0xac, oper: exec::res::default(),  fmt: "RES 5, H",    },
    Instruction { code: 0xad, oper: exec::res::default(),  fmt: "RES 5, L",    },
    Instruction { code: 0xae, oper: exec::res::default(),  fmt: "RES 5, (HL)", },
    Instruction { code: 0xaf, oper: exec::res::default(),  fmt: "RES 5, A",    },
    Instruction { code: 0xb0, oper: exec::res::default(),  fmt: "RES 6, B",    },
    Instruction { code: 0xb1, oper: exec::res::default(),  fmt: "RES 6, C",    },
    Instruction { code: 0xb2, oper: exec::res::default(),  fmt: "RES 6, D",    },
    Instruction { code: 0xb3, oper: exec::res::default(),  fmt: "RES 6, E",    },
    Instruction { code: 0xb4, oper: exec::res::default(),  fmt: "RES 6, H",    },
    Instruction { code: 0xb5, oper: exec::res::default(),  fmt: "RES 6, L",    },
    Instruction { code: 0xb6, oper: exec::res::default(),  fmt: "RES 6, (HL)", },
    Instruction { code: 0xb7, oper: exec::res::default(),  fmt: "RES 6, A",    },
    Instruction { code: 0xb8, oper: exec::res::default(),  fmt: "RES 7, B",    },
    Instruction { code: 0xb9, oper: exec::res::default(),  fmt: "RES 7, C",    },
    Instruction { code: 0xba, oper: exec::res::default(),  fmt: "RES 7, D",    },
    Instruction { code: 0xbb, oper: exec::res::default(),  fmt: "RES 7, E",    },
    Instruction { code: 0xbc, oper: exec::res::default(),  fmt: "RES 7, H",    },
    Instruction { code: 0xbd, oper: exec::res::default(),  fmt: "RES 7, L",    },
    Instruction { code: 0xbe, oper: exec::res::default(),  fmt: "RES 7, (HL)", },
    Instruction { code: 0xbf, oper: exec::res::default(),  fmt: "RES 7, A",    },
    Instruction { code: 0xc0, oper: exec::set::default(),  fmt: "SET 0, B",    },
    Instruction { code: 0xc1, oper: exec::set::default(),  fmt: "SET 0, C",    },
    Instruction { code: 0xc2, oper: exec::set::default(),  fmt: "SET 0, D",    },
    Instruction { code: 0xc3, oper: exec::set::default(),  fmt: "SET 0, E",    },
    Instruction { code: 0xc4, oper: exec::set::default(),  fmt: "SET 0, H",    },
    Instruction { code: 0xc5, oper: exec::set::default(),  fmt: "SET 0, L",    },
    Instruction { code: 0xc6, oper: exec::set::default(),  fmt: "SET 0, (HL)", },
    Instruction { code: 0xc7, oper: exec::set::default(),  fmt: "SET 0, A",    },
    Instruction { code: 0xc8, oper: exec::set::default(),  fmt: "SET 1, B",    },
    Instruction { code: 0xc9, oper: exec::set::default(),  fmt: "SET 1, C",    },
    Instruction { code: 0xca, oper: exec::set::default(),  fmt: "SET 1, D",    },
    Instruction { code: 0xcb, oper: exec::set::default(),  fmt: "SET 1, E",    },
    Instruction { code: 0xcc, oper: exec::set::default(),  fmt: "SET 1, H",    },
    Instruction { code: 0xcd, oper: exec::set::default(),  fmt: "SET 1, L",    },
    Instruction { code: 0xce, oper: exec::set::default(),  fmt: "SET 1, (HL)", },
    Instruction { code: 0xcf, oper: exec::set::default(),  fmt: "SET 1, A",    },
    Instruction { code: 0xd0, oper: exec::set::default(),  fmt: "SET 2, B",    },
    Instruction { code: 0xd1, oper: exec::set::default(),  fmt: "SET 2, C",    },
    Instruction { code: 0xd2, oper: exec::set::default(),  fmt: "SET 2, D",    },
    Instruction { code: 0xd3, oper: exec::set::default(),  fmt: "SET 2, E",    },
    Instruction { code: 0xd4, oper: exec::set::default(),  fmt: "SET 2, H",    },
    Instruction { code: 0xd5, oper: exec::set::default(),  fmt: "SET 2, L",    },
    Instruction { code: 0xd6, oper: exec::set::default(),  fmt: "SET 2, (HL)", },
    Instruction { code: 0xd7, oper: exec::set::default(),  fmt: "SET 2, A",    },
    Instruction { code: 0xd8, oper: exec::set::default(),  fmt: "SET 3, B",    },
    Instruction { code: 0xd9, oper: exec::set::default(),  fmt: "SET 3, C",    },
    Instruction { code: 0xda, oper: exec::set::default(),  fmt: "SET 3, D",    },
    Instruction { code: 0xdb, oper: exec::set::default(),  fmt: "SET 3, E",    },
    Instruction { code: 0xdc, oper: exec::set::default(),  fmt: "SET 3, H",    },
    Instruction { code: 0xdd, oper: exec::set::default(),  fmt: "SET 3, L",    },
    Instruction { code: 0xde, oper: exec::set::default(),  fmt: "SET 3, (HL)", },
    Instruction { code: 0xdf, oper: exec::set::default(),  fmt: "SET 3, A",    },
    Instruction { code: 0xe0, oper: exec::set::default(),  fmt: "SET 4, B",    },
    Instruction { code: 0xe1, oper: exec::set::default(),  fmt: "SET 4, C",    },
    Instruction { code: 0xe2, oper: exec::set::default(),  fmt: "SET 4, D",    },
    Instruction { code: 0xe3, oper: exec::set::default(),  fmt: "SET 4, E",    },
    Instruction { code: 0xe4, oper: exec::set::default(),  fmt: "SET 4, H",    },
    Instruction { code: 0xe5, oper: exec::set::default(),  fmt: "SET 4, L",    },
    Instruction { code: 0xe6, oper: exec::set::default(),  fmt: "SET 4, (HL)", },
    Instruction { code: 0xe7, oper: exec::set::default(),  fmt: "SET 4, A",    },
    Instruction { code: 0xe8, oper: exec::set::default(),  fmt: "SET 5, B",    },
    Instruction { code: 0xe9, oper: exec::set::default(),  fmt: "SET 5, C",    },
    Instruction { code: 0xea, oper: exec::set::default(),  fmt: "SET 5, D",    },
    Instruction { code: 0xeb, oper: exec::set::default(),  fmt: "SET 5, E",    },
    Instruction { code: 0xec, oper: exec::set::default(),  fmt: "SET 5, H",    },
    Instruction { code: 0xed, oper: exec::set::default(),  fmt: "SET 5, L",    },
    Instruction { code: 0xee, oper: exec::set::default(),  fmt: "SET 5, (HL)", },
    Instruction { code: 0xef, oper: exec::set::default(),  fmt: "SET 5, A",    },
    Instruction { code: 0xf0, oper: exec::set::default(),  fmt: "SET 6, B",    },
    Instruction { code: 0xf1, oper: exec::set::default(),  fmt: "SET 6, C",    },
    Instruction { code: 0xf2, oper: exec::set::default(),  fmt: "SET 6, D",    },
    Instruction { code: 0xf3, oper: exec::set::default(),  fmt: "SET 6, E",    },
    Instruction { code: 0xf4, oper: exec::set::default(),  fmt: "SET 6, H",    },
    Instruction { code: 0xf5, oper: exec::set::default(),  fmt: "SET 6, L",    },
    Instruction { code: 0xf6, oper: exec::set::default(),  fmt: "SET 6, (HL)", },
    Instruction { code: 0xf7, oper: exec::set::default(),  fmt: "SET 6, A",    },
    Instruction { code: 0xf8, oper: exec::set::default(),  fmt: "SET 7, B",    },
    Instruction { code: 0xf9, oper: exec::set::default(),  fmt: "SET 7, C",    },
    Instruction { code: 0xfa, oper: exec::set::default(),  fmt: "SET 7, D",    },
    Instruction { code: 0xfb, oper: exec::set::default(),  fmt: "SET 7, E",    },
    Instruction { code: 0xfc, oper: exec::set::default(),  fmt: "SET 7, H",    },
    Instruction { code: 0xfd, oper: exec::set::default(),  fmt: "SET 7, L",    },
    Instruction { code: 0xfe, oper: exec::set::default(),  fmt: "SET 7, (HL)", },
    Instruction { code: 0xff, oper: exec::set::default(),  fmt: "SET 7, A",    },
];
